import path from 'path';

import postcss from 'postcss';
import postcssModules from 'postcss-modules';
import glob from 'fast-glob';
import fs from 'fs-extra';
import * as R from 'ramda';

import { generateScopedName } from './name';

const outputFolder = path.resolve(__dirname, '../../css');
fs.ensureDirSync(outputFolder);

const makeName = (filePath: string) => {
  const additional = ['utility.module.css'];

  let fileName = filePath.split('/src/')[1];

  if (filePath.includes('utilities/')) {
    fileName = fileName.split('utilities/')[1].split('/')[0];
  }

  if (fileName.includes('legacy/')) {
    fileName = fileName.split('legacy/')[1].split('/')[0];
  }

  const name = fileName
    .split('/')
    .find(
      (partial) =>
        partial[0] === partial[0].toUpperCase() || additional.includes(partial),
    );

  if (!name) {
    throw new Error(`Could not make name from ${fileName} at ${filePath}`);
  }

  return name;
};

const withFileHeader = (css: string, file: string) =>
  `/** This css file was autogenerated from ${file} **/\n${css}`;

async function createFiles() {
  console.log('🏗️  Started building css files...');

  const modules = glob.sync(
    path.resolve(__dirname, '../src/**/*.module.css').replace(/\\/g, '/'),
  );

  // group files that are under src/components/{THIS IS THE NAME}
  const components = modules.reduce<{ [key: string]: string[] }>(
    (components, filePath) => {
      const name = makeName(filePath);

      components[name] = !components[name]
        ? [filePath]
        : [...components[name], filePath];

      return components;
    },
    {},
  );

  // console.log({ components });

  const generatedComponents: string[] = [];

  // go over the components, and create a file that contains all the css for that component
  await Promise.all(
    Object.entries(components).map(async ([componentName, files]) => {
      componentName = componentName.toLowerCase().split('.')[0];

      const result = await postcss([
        postcssModules({
          generateScopedName,
          getJSON: () => {
            return;
          },
          scopeBehaviour: 'local',
        }),
      ]).process(
        files.map((file) => fs.readFileSync(file, 'utf-8')).join('\n'),
        {
          from: path.basename(files[0]),
        },
      );

      const cssContent = withFileHeader(
        result.css,
        R.defaultTo('')(R.last(files[0].split('/'))),
      );

      if (files[0].includes('legacy')) {
        // if legacy folder does not exist, create it
        if (!fs.existsSync(path.join(outputFolder, 'legacy'))) {
          fs.mkdirSync(path.join(outputFolder, 'legacy'));
        }

        generatedComponents.push(
          path
            .join(outputFolder, 'legacy', `${componentName}.css`)
            .replace(/\\/g, '/')
            .split('/css/')[1],
        );

        return fs.writeFile(
          path.join(outputFolder, 'legacy', `${componentName}.css`),
          cssContent,
        );
      }

      if (files[0].includes('utilities')) {
        // if utilities folder does not exist, create it
        if (!fs.existsSync(path.join(outputFolder, 'utilities'))) {
          fs.mkdirSync(path.join(outputFolder, 'utilities'));
        }

        generatedComponents.push(
          path
            .join(outputFolder, 'utilities', `${componentName}.css`)
            .replace(/\\/g, '/')
            .split('/css/')[1],
        );

        return fs.writeFile(
          path.join(outputFolder, 'utilities', `${componentName}.css`),
          cssContent,
        );
      }

      generatedComponents.push(
        path
          .join(outputFolder, `${componentName}.css`)
          .replace(/\\/g, '/')
          .split('/css/')[1],
      );

      return fs.writeFile(
        path.join(outputFolder, `${componentName}.css`),
        cssContent,
      );
    }),
  ).then(() => {
    const [utilityFiles, componentFiles] = R.partition(
      R.includes('utilities/'),
      generatedComponents,
    );

    createUtilities(utilityFiles);
    createIndex(['utilities.css', ...componentFiles]);
  });

  console.log('\n🏁 Finished building css files!');
}

function createUtilities(utlityFiles: string[]) {
  const cssFilesContent = utlityFiles.map((file) => `@import url('${file}');`);
  fs.writeFileSync(
    path.join(outputFolder, 'utilities.css'),
    cssFilesContent.join('\n'),
  );
}

function createIndex(cssFiles: string[]) {
  const cssFilesContent = cssFiles.map((file) => `@import url('${file}');`);
  fs.writeFileSync(
    path.join(outputFolder, 'index.css'),
    `@charset "UTF-8";\n${cssFilesContent.join('\n')}\n`,
  );

  console.log('\n👷 Created CSS files: \n ', cssFiles);
}

void createFiles();
