plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.4.1.cjs

npmAuthToken: ${NODE_AUTH_TOKEN:-}
enableTelemetry: false

nodeLinker: 'node-modules'
