packages:
  - packages/*
  - apps/*
  - plugins/*
  - internal/*
  - '!internal/design-tokens'
ignoredBuiltDependencies:
  - '@bundled-es-modules/glob'
  - sharp
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - esbuild
  - just-pnpm
  - style-dictionary
useNodeVersion: 22.21.1
packageExtensions:
  '@navikt/aksel-icons':
    peerDependencies:
      react: ">=18.3.1 || ^19.0.0"
    peerDependenciesMeta:
      react:
        optional: true
syncInjectedDepsAfterScripts:
  - build
  - build:all
  - build:www
  - build:themebuilder
  - build:storybook
injectWorkspacePackages: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@u-elements/*"
