packages:
  - packages/*
  - apps/*
  - plugins/*
  - internal/*
injectWorkspacePackages: true
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@u-elements/*"
allowBuilds:
  "@biomejs/biome": true
  "@swc/core": true
  esbuild: true
  style-dictionary: true
  "@bundled-es-modules/glob": false
  "@parcel/watcher": false
  "rs-module-lexer": false
  "sharp": false
packageExtensions:
  "@navikt/aksel-icons":
    peerDependencies:
      react: ">=18.3.1 || ^19.0.0"
    peerDependenciesMeta:
      react:
        optional: true
syncInjectedDepsAfterScripts:
  - build
  - build:all
  - build:www
  - build:themebuilder
  - build:storybook
useNodeVersion: 24.15.0
blockExoticSubdeps: true
