export { CodeSnippet } from './CodeSnippet/CodeSnippet';
export { Container } from './Container/Container';
export { ClipboardButton } from './ClipboardButton/ClipboardButton';
export { ColorModal } from './ColorModal/ColorModal';
export { Header } from './Header/Header';
export { Figma } from './logos/Figma';
export { Github } from './logos/Github';
export { Slack } from './logos/Slack';
export { Footer } from './Footer/Footer';
