name: Create tokens 💲
description: This template is for internal use when we need to define tokens for a component
title: "Tokens for: "
labels: ["tokens"]
body:

  - type: input
    id: component
    attributes:
      label: What component needs tokens?
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        If there are specific tokens you need, edit the textarea underneath to mirror your needs.

  - type: textarea
    id: tokens
    attributes:
      label: Tokens
      value: |
        ```
        Replace with size tokens

        Replace with padding

        Replace with colors

        Replace with border width

        Replace with text
        ```

  - type: textarea
    id: tokens
    attributes:
      label: Tokens
      value: |
        - [ ] Tokens are published and ready for use
          - [ ] The size is described with tokens
          - [ ] spacing is described with tokens
          - [ ] The color of all states are described with tokens
          - [ ] Border width or styling is described with tokens
          - [ ] Text size are described with tokens

