/**
 * Do not edit directly
 * These files are generated from design tokens defined in Figma using Token Studio
 */

export const color = [
  {
    value: '#E6EFF8',
    type: 'color',
    description: 'AAA 12.8 on grey 800\nAA 6.4 as bkdg for interaction blue',
    filePath: '../../design-tokens/Brand/Altinn.json',
    isSource: false,
    original: {
      value: '#E6EFF8',
      type: 'color',
      description: 'AAA 12.8 on grey 800\nAA 6.4 as bkdg for interaction blue',
    },
    name: 'brand_primary_100',
    attributes: {},
    path: ['brand', 'primary', '100'],
  },
  {
    value: '#B3D0EA',
    type: 'color',
    description:
      'Light error color\nAAA 11.4 on grey 800\nAA 5.7 as bkdg for interaction blue',
    filePath: '../../design-tokens/Brand/Altinn.json',
    isSource: false,
    original: {
      value: '#B3D0EA',
      type: 'color',
      description:
        'Light error color\nAAA 11.4 on grey 800\nAA 5.7 as bkdg for interaction blue',
    },
    name: 'brand_primary_200',
    attributes: {},
    path: ['brand', 'primary', '200'],
  },
  {
    value: '#80B1DD',
    type: 'color',
    description: 'AAA 9 on grey 800\nAA 4.5 as bkdg for interaction blue',
    filePath: '../../design-tokens/Brand/Altinn.json',
    isSource: false,
    original: {
      value: '#80B1DD',
      type: 'color',
      description: 'AAA 9 on grey 800\nAA 4.5 as bkdg for interaction blue',
    },
    name: 'brand_primary_300',
    attributes: {},
    path: ['brand', 'primary', '300'],
  },
  {
    value: '#66A1D6',
    type: 'color',
    description: 'AAA 7.1 on grey 800\nAA18 3.5 as bkdg for interaction blue',
    filePath: '../../design-tokens/Brand/Altinn.json',
    isSource: false,
    original: {
      value: '#66A1D6',
      type: 'color',
      description: 'AAA 7.1 on grey 800\nAA18 3.5 as bkdg for interaction blue',
    },
    name: 'brand_primary_400',
    attributes: {},
    path: ['brand', 'primary', '400'],
  },
  {
    value: '#3381C8',
    type: 'color',
    description: 'AA 5.6 on grey 800',
    filePath: '../../design-tokens/Brand/Altinn.json',
    isSource: false,
    original: {
      value: '#3381C8',
      type: 'color',
      description: 'AA 5.6 on grey 800',
    },
    name: 'brand_primary_500',
    attributes: {},
    path: ['brand', 'primary', '500'],
  },
  {
    value: '#1A72C1',
    type: 'color',
    description: 'AA 4.5 on grey 800',
    filePath: '../../design-tokens/Brand/Altinn.json',
    isSource: false,
    original: {
      value: '#1A72C1',
      type: 'color',
      description: 'AA 4.5 on grey 800',
    },
    name: 'brand_primary_600',
    attributes: {},
    path: ['brand', 'primary', '600'],
  },
  {
    value: '#0062BA',
    type: 'color',
    description: 'AA18 3.7 on grey 800',
    filePath: '../../design-tokens/Brand/Altinn.json',
    isSource: false,
    original: {
      value: '#0062BA',
      type: 'color',
      description: 'AA18 3.7 on grey 800',
    },
    name: 'brand_primary_700',
    attributes: {},
    path: ['brand', 'primary', '700'],
  },
  {
    value: '#004E95',
    type: 'color',
    description: 'AA 4.7 on white',
    filePath: '../../design-tokens/Brand/Altinn.json',
    isSource: false,
    original: {
      value: '#004E95',
      type: 'color',
      description: 'AA 4.7 on white',
    },
    name: 'brand_primary_800',
    attributes: {},
    path: ['brand', 'primary', '800'],
  },
  {
    value: '#00315D',
    type: 'color',
    description: 'AA 4.7 on white',
    filePath: '../../design-tokens/Brand/Altinn.json',
    isSource: false,
    original: {
      value: '#00315D',
      type: 'color',
      description: 'AA 4.7 on white',
    },
    name: 'brand_primary_900',
    attributes: {},
    path: ['brand', 'primary', '900'],
  },
  {
    value: '#DCD6EA',
    type: 'color',
    description: 'AAA 13.3 on grey 800\nAA 6.7 as bkdg for interaction blue',
    filePath: '../../design-tokens/Brand/Altinn.json',
    isSource: false,
    original: {
      value: '#DCD6EA',
      type: 'color',
      description: 'AAA 13.3 on grey 800\nAA 6.7 as bkdg for interaction blue',
    },
    name: 'brand_secondary_100',
    attributes: {},
    path: ['brand', 'secondary', '100'],
  },
  {
    value: '#C5BBDD',
    type: 'color',
    description:
      'Light warning color\nAAA 12.3 on grey 800\nAA 1.1 as bkdg for interaction blue',
    filePath: '../../design-tokens/Brand/Altinn.json',
    isSource: false,
    original: {
      value: '#C5BBDD',
      type: 'color',
      description:
        'Light warning color\nAAA 12.3 on grey 800\nAA 1.1 as bkdg for interaction blue',
    },
    name: 'brand_secondary_200',
    attributes: {},
    path: ['brand', 'secondary', '200'],
  },
  {
    value: '#A392C8',
    type: 'color',
    description: 'AAA 10 on grey 800\nAA 5.4 as bkdg for interaction blue',
    filePath: '../../design-tokens/Brand/Altinn.json',
    isSource: false,
    original: {
      value: '#A392C8',
      type: 'color',
      description: 'AAA 10 on grey 800\nAA 5.4 as bkdg for interaction blue',
    },
    name: 'brand_secondary_300',
    attributes: {},
    path: ['brand', 'secondary', '300'],
  },
  {
    value: '#806AB4',
    type: 'color',
    description: 'AAA 9.2 on grey 800\nAA 4.6 as bkdg for interaction blue',
    filePath: '../../design-tokens/Brand/Altinn.json',
    isSource: false,
    original: {
      value: '#806AB4',
      type: 'color',
      description: 'AAA 9.2 on grey 800\nAA 4.6 as bkdg for interaction blue',
    },
    name: 'brand_secondary_400',
    attributes: {},
    path: ['brand', 'secondary', '400'],
  },
  {
    value: '#6A52A3',
    type: 'color',
    description: 'AAA 7.9 on grey 800\nAA18 4 as bkdg for interaction blue',
    filePath: '../../design-tokens/Brand/Altinn.json',
    isSource: false,
    original: {
      value: '#6A52A3',
      type: 'color',
      description: 'AAA 7.9 on grey 800\nAA18 4 as bkdg for interaction blue',
    },
    name: 'brand_secondary_500',
    attributes: {},
    path: ['brand', 'secondary', '500'],
  },
  {
    value: '#594488',
    type: 'color',
    description: 'AA 6.8 on grey 800\nAA18 3.4 as bkdg for interaction blue',
    filePath: '../../design-tokens/Brand/Altinn.json',
    isSource: false,
    original: {
      value: '#594488',
      type: 'color',
      description: 'AA 6.8 on grey 800\nAA18 3.4 as bkdg for interaction blue',
    },
    name: 'brand_secondary_600',
    attributes: {},
    path: ['brand', 'secondary', '600'],
  },
  {
    value: '#3F3161',
    type: 'color',
    description: 'AA 5.5 on grey 800',
    filePath: '../../design-tokens/Brand/Altinn.json',
    isSource: false,
    original: {
      value: '#3F3161',
      type: 'color',
      description: 'AA 5.5 on grey 800',
    },
    name: 'brand_secondary_700',
    attributes: {},
    path: ['brand', 'secondary', '700'],
  },
  {
    value: '#352951',
    type: 'color',
    description: 'AA18 4.4 on grey 800\nAA18 3.2 on white',
    filePath: '../../design-tokens/Brand/Altinn.json',
    isSource: false,
    original: {
      value: '#352951',
      type: 'color',
      description: 'AA18 4.4 on grey 800\nAA18 3.2 on white',
    },
    name: 'brand_secondary_800',
    attributes: {},
    path: ['brand', 'secondary', '800'],
  },
  {
    value: '#231B36',
    type: 'color',
    description: 'AA18 4.4 on grey 800\nAA18 3.2 on white',
    filePath: '../../design-tokens/Brand/Altinn.json',
    isSource: false,
    original: {
      value: '#231B36',
      type: 'color',
      description: 'AA18 4.4 on grey 800\nAA18 3.2 on white',
    },
    name: 'brand_secondary_900',
    attributes: {},
    path: ['brand', 'secondary', '900'],
  },
  {
    value: '#F9D5DB',
    type: 'color',
    description: 'AAA 12.9 on grey 800\nAA 6.5 as bkdg for interaction blue',
    filePath: '../../design-tokens/Brand/Altinn.json',
    isSource: false,
    original: {
      value: '#F9D5DB',
      type: 'color',
      description: 'AAA 12.9 on grey 800\nAA 6.5 as bkdg for interaction blue',
    },
    name: 'brand_tertiary_100',
    attributes: {},
    path: ['brand', 'tertiary', '100'],
  },
  {
    value: '#F3ABB6',
    type: 'color',
    description:
      'Light information color \nAAA 11.5 on grey 800\nAA 5.8 as bkdg for interaction blue',
    filePath: '../../design-tokens/Brand/Altinn.json',
    isSource: false,
    original: {
      value: '#F3ABB6',
      type: 'color',
      description:
        'Light information color \nAAA 11.5 on grey 800\nAA 5.8 as bkdg for interaction blue',
    },
    name: 'brand_tertiary_200',
    attributes: {},
    path: ['brand', 'tertiary', '200'],
  },
  {
    value: '#EC8292',
    type: 'color',
    description: 'AAA 9.2 on grey 800\nAA 4.6 as bkdg for interaction blue',
    filePath: '../../design-tokens/Brand/Altinn.json',
    isSource: false,
    original: {
      value: '#EC8292',
      type: 'color',
      description: 'AAA 9.2 on grey 800\nAA 4.6 as bkdg for interaction blue',
    },
    name: 'brand_tertiary_300',
    attributes: {},
    path: ['brand', 'tertiary', '300'],
  },
  {
    value: '#E6586D',
    type: 'color',
    description: 'AAA 7.3 on grey 800\nAA18 3.7 as bkdg for interaction blue',
    filePath: '../../design-tokens/Brand/Altinn.json',
    isSource: false,
    original: {
      value: '#E6586D',
      type: 'color',
      description: 'AAA 7.3 on grey 800\nAA18 3.7 as bkdg for interaction blue',
    },
    name: 'brand_tertiary_400',
    attributes: {},
    path: ['brand', 'tertiary', '400'],
  },
  {
    value: '#E02E49',
    type: 'color',
    description: 'AA 5.8 on grey 800',
    filePath: '../../design-tokens/Brand/Altinn.json',
    isSource: false,
    original: {
      value: '#E02E49',
      type: 'color',
      description: 'AA 5.8 on grey 800',
    },
    name: 'brand_tertiary_500',
    attributes: {},
    path: ['brand', 'tertiary', '500'],
  },
  {
    value: '#B3253A',
    type: 'color',
    description: 'AA 4.6 on grey 800',
    filePath: '../../design-tokens/Brand/Altinn.json',
    isSource: false,
    original: {
      value: '#B3253A',
      type: 'color',
      description: 'AA 4.6 on grey 800',
    },
    name: 'brand_tertiary_600',
    attributes: {},
    path: ['brand', 'tertiary', '600'],
  },
  {
    value: '#861C2C',
    type: 'color',
    description: 'AA18 3.8 on grey 800',
    filePath: '../../design-tokens/Brand/Altinn.json',
    isSource: false,
    original: {
      value: '#861C2C',
      type: 'color',
      description: 'AA18 3.8 on grey 800',
    },
    name: 'brand_tertiary_700',
    attributes: {},
    path: ['brand', 'tertiary', '700'],
  },
  {
    value: '#5A121D',
    type: 'color',
    description: 'AA 5.6 on white',
    filePath: '../../design-tokens/Brand/Altinn.json',
    isSource: false,
    original: {
      value: '#5A121D',
      type: 'color',
      description: 'AA 5.6 on white',
    },
    name: 'brand_tertiary_800',
    attributes: {},
    path: ['brand', 'tertiary', '800'],
  },
  {
    value: '#480e17',
    type: 'color',
    description: 'AA 5.6 on white',
    filePath: '../../design-tokens/Brand/Altinn.json',
    isSource: false,
    original: {
      value: '#480e17',
      type: 'color',
      description: 'AA 5.6 on white',
    },
    name: 'brand_tertiary_900',
    attributes: {},
    path: ['brand', 'tertiary', '900'],
  },
  {
    value: '#0062ba',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.700}',
      type: 'color',
    },
    name: 'semantic_surface_action_primary_default',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'primary', 'default'],
  },
  {
    value: '#004e95',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.800}',
      type: 'color',
    },
    name: 'semantic_surface_action_primary_hover',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'primary', 'hover'],
  },
  {
    value: '#00315d',
    type: 'color',
    description: 'Standard farge for handlinger',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.900}',
      type: 'color',
      description: 'Standard farge for handlinger',
    },
    name: 'semantic_surface_action_primary_active',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'primary', 'active'],
  },
  {
    value: '#e6eff8',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.100}',
      type: 'color',
    },
    name: 'semantic_surface_action_primary_subtle',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'primary', 'subtle'],
  },
  {
    value: '#b3d0ea',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.200}',
      type: 'color',
    },
    name: 'semantic_surface_action_primary_subtle_hover',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'primary', 'subtle-hover'],
  },
  {
    value: '#ffffff',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.white}',
      type: 'color',
    },
    name: 'semantic_surface_action_primary_no_fill',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'primary', 'no_fill'],
  },
  {
    value: '#e6eff8',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.100}',
      type: 'color',
    },
    name: 'semantic_surface_action_primary_no_fill_hover',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'primary', 'no_fill-hover'],
  },
  {
    value: '#b3d0ea',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.200}',
      type: 'color',
    },
    name: 'semantic_surface_action_primary_no_fill_active',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'primary', 'no_fill-active'],
  },
  {
    value: '#00315d',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.900}',
      type: 'color',
    },
    name: 'semantic_surface_action_secondary_default',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'secondary', 'default'],
  },
  {
    value: 'rgba(#00315d, 0.9)',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: 'rgba({colors.blue.900}, 0.9)',
      type: 'color',
    },
    name: 'semantic_surface_action_secondary_hover',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'secondary', 'hover'],
  },
  {
    value: 'rgba(#00315d, 0.8)',
    type: 'color',
    description: 'Standard farge for handlinger',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: 'rgba({colors.blue.900}, 0.8)',
      type: 'color',
      description: 'Standard farge for handlinger',
    },
    name: 'semantic_surface_action_secondary_active',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'secondary', 'active'],
  },
  {
    value: '#f4f5f6',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.100}',
      type: 'color',
    },
    name: 'semantic_surface_action_secondary_subtle',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'secondary', 'subtle'],
  },
  {
    value: '#e9eaec',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.200}',
      type: 'color',
    },
    name: 'semantic_surface_action_secondary_subtle_hover',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'secondary', 'subtle-hover'],
  },
  {
    value: '#ffffff',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.white}',
      type: 'color',
    },
    name: 'semantic_surface_action_secondary_no_fill',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'secondary', 'no_fill'],
  },
  {
    value: 'rgba(#00315d, 0.1)',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: 'rgba({colors.blue.900}, 0.1)',
      type: 'color',
    },
    name: 'semantic_surface_action_secondary_no_fill_hover',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'secondary', 'no_fill-hover'],
  },
  {
    value: 'rgba(#00315d, 0.2)',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: 'rgba({colors.blue.900}, 0.2)',
      type: 'color',
    },
    name: 'semantic_surface_action_secondary_no_fill_active',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'secondary', 'no_fill-active'],
  },
  {
    value: '#ffffff',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.white}',
      type: 'color',
    },
    name: 'semantic_surface_neutral_default',
    attributes: {},
    path: ['semantic', 'surface', 'neutral', 'default'],
  },
  {
    value: '#e6eff8',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.100}',
      type: 'color',
    },
    name: 'semantic_surface_neutral_selected',
    attributes: {},
    path: ['semantic', 'surface', 'neutral', 'selected'],
  },
  {
    value: '#f4f5f6',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.100}',
      type: 'color',
    },
    name: 'semantic_surface_neutral_subtle',
    attributes: {},
    path: ['semantic', 'surface', 'neutral', 'subtle'],
  },
  {
    value: '#e9eaec',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.200}',
      type: 'color',
    },
    name: 'semantic_surface_neutral_subtle_hover',
    attributes: {},
    path: ['semantic', 'surface', 'neutral', 'subtle-hover'],
  },
  {
    value: '#68707c',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.600}',
      type: 'color',
    },
    name: 'semantic_surface_neutral_dark',
    attributes: {},
    path: ['semantic', 'surface', 'neutral', 'dark'],
  },
  {
    value: '#1e2b3c',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.800}',
      type: 'color',
    },
    name: 'semantic_surface_neutral_inverted',
    attributes: {},
    path: ['semantic', 'surface', 'neutral', 'inverted'],
  },
  {
    value: '#d1f4e1',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.green.200}',
      type: 'color',
    },
    name: 'semantic_surface_success_subtle',
    attributes: {},
    path: ['semantic', 'surface', 'success', 'subtle'],
  },
  {
    value: '#8be4b5',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.green.300}',
      type: 'color',
    },
    name: 'semantic_surface_success_subtle_hover',
    attributes: {},
    path: ['semantic', 'surface', 'success', 'subtle-hover'],
  },
  {
    value: '#118849',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.green.700}',
      type: 'color',
    },
    name: 'semantic_surface_success_default',
    attributes: {},
    path: ['semantic', 'surface', 'success', 'default'],
  },
  {
    value: '#0c6536',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.green.800}',
      type: 'color',
    },
    name: 'semantic_surface_success_hover',
    attributes: {},
    path: ['semantic', 'surface', 'success', 'hover'],
  },
  {
    value: '#084826',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.green.900}',
      type: 'color',
    },
    name: 'semantic_surface_success_active',
    attributes: {},
    path: ['semantic', 'surface', 'success', 'active'],
  },
  {
    value: '#ffffff',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.white}',
      type: 'color',
    },
    name: 'semantic_surface_success_no_fill',
    attributes: {},
    path: ['semantic', 'surface', 'success', 'no_fill'],
  },
  {
    value: '#d1f4e1',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.green.200}',
      type: 'color',
    },
    name: 'semantic_surface_success_no_fill_hover',
    attributes: {},
    path: ['semantic', 'surface', 'success', 'no_fill-hover'],
  },
  {
    value: '#8be4b5',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.green.300}',
      type: 'color',
    },
    name: 'semantic_surface_success_no_fill_active',
    attributes: {},
    path: ['semantic', 'surface', 'success', 'no_fill-active'],
  },
  {
    value: '#fffbe6',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.yellow.100}',
      type: 'color',
    },
    name: 'semantic_surface_warning_subtle',
    attributes: {},
    path: ['semantic', 'surface', 'warning', 'subtle'],
  },
  {
    value: '#fff4b4',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.yellow.200}',
      type: 'color',
    },
    name: 'semantic_surface_warning_subtle_hover',
    attributes: {},
    path: ['semantic', 'surface', 'warning', 'subtle-hover'],
  },
  {
    value: '#ff8c06',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.orange.500}',
      type: 'color',
    },
    name: 'semantic_surface_warning_default',
    attributes: {},
    path: ['semantic', 'surface', 'warning', 'default'],
  },
  {
    value: '#f9d5db',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.red.100}',
      type: 'color',
    },
    name: 'semantic_surface_danger_subtle',
    attributes: {},
    path: ['semantic', 'surface', 'danger', 'subtle'],
  },
  {
    value: '#f3abb6',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.red.200}',
      type: 'color',
    },
    name: 'semantic_surface_danger_subtle_hover',
    attributes: {},
    path: ['semantic', 'surface', 'danger', 'subtle-hover'],
  },
  {
    value: '#e02e49',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.red.500}',
      type: 'color',
    },
    name: 'semantic_surface_danger_default',
    attributes: {},
    path: ['semantic', 'surface', 'danger', 'default'],
  },
  {
    value: '#b3253a',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.red.600}',
      type: 'color',
    },
    name: 'semantic_surface_danger_hover',
    attributes: {},
    path: ['semantic', 'surface', 'danger', 'hover'],
  },
  {
    value: '#861c2c',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.red.700}',
      type: 'color',
    },
    name: 'semantic_surface_danger_active',
    attributes: {},
    path: ['semantic', 'surface', 'danger', 'active'],
  },
  {
    value: '#ffffff',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.white}',
      type: 'color',
    },
    name: 'semantic_surface_danger_no_fill',
    attributes: {},
    path: ['semantic', 'surface', 'danger', 'no_fill'],
  },
  {
    value: '#f9d5db',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.red.100}',
      type: 'color',
    },
    name: 'semantic_surface_danger_no_fill_hover',
    attributes: {},
    path: ['semantic', 'surface', 'danger', 'no_fill-hover'],
  },
  {
    value: '#f3abb6',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.red.200}',
      type: 'color',
    },
    name: 'semantic_surface_danger_no_fill_active',
    attributes: {},
    path: ['semantic', 'surface', 'danger', 'no_fill-active'],
  },
  {
    value: '#e6eff8',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.100}',
      type: 'color',
    },
    name: 'semantic_surface_info_subtle',
    attributes: {},
    path: ['semantic', 'surface', 'info', 'subtle'],
  },
  {
    value: '#b3d0ea',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.200}',
      type: 'color',
    },
    name: 'semantic_surface_info_subtle_hover',
    attributes: {},
    path: ['semantic', 'surface', 'info', 'subtle-hover'],
  },
  {
    value: '#B3D0EA',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{brand.primary.200}',
      type: 'color',
    },
    name: 'semantic_surface_primary_light',
    attributes: {},
    path: ['semantic', 'surface', 'primary', 'light'],
  },
  {
    value: '#80B1DD',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{brand.primary.300}',
      type: 'color',
    },
    name: 'semantic_surface_primary_light_hover',
    attributes: {},
    path: ['semantic', 'surface', 'primary', 'light-hover'],
  },
  {
    value: '#66A1D6',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{brand.primary.400}',
      type: 'color',
    },
    name: 'semantic_surface_primary_light_active',
    attributes: {},
    path: ['semantic', 'surface', 'primary', 'light-active'],
  },
  {
    value: '#004E95',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{brand.primary.800}',
      type: 'color',
    },
    name: 'semantic_surface_primary_dark',
    attributes: {},
    path: ['semantic', 'surface', 'primary', 'dark'],
  },
  {
    value: '#C5BBDD',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{brand.secondary.200}',
      type: 'color',
    },
    name: 'semantic_surface_secondary_light',
    attributes: {},
    path: ['semantic', 'surface', 'secondary', 'light'],
  },
  {
    value: '#A392C8',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{brand.secondary.300}',
      type: 'color',
    },
    name: 'semantic_surface_secondary_light_hover',
    attributes: {},
    path: ['semantic', 'surface', 'secondary', 'light-hover'],
  },
  {
    value: '#806AB4',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{brand.secondary.400}',
      type: 'color',
    },
    name: 'semantic_surface_secondary_light_active',
    attributes: {},
    path: ['semantic', 'surface', 'secondary', 'light-active'],
  },
  {
    value: '#231B36',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{brand.secondary.900}',
      type: 'color',
    },
    name: 'semantic_surface_secondary_dark',
    attributes: {},
    path: ['semantic', 'surface', 'secondary', 'dark'],
  },
  {
    value: '#F3ABB6',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{brand.tertiary.200}',
      type: 'color',
    },
    name: 'semantic_surface_tertiary_light',
    attributes: {},
    path: ['semantic', 'surface', 'tertiary', 'light'],
  },
  {
    value: '#EC8292',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{brand.tertiary.300}',
      type: 'color',
    },
    name: 'semantic_surface_tertiary_light_hover',
    attributes: {},
    path: ['semantic', 'surface', 'tertiary', 'light-hover'],
  },
  {
    value: '#E6586D',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{brand.tertiary.400}',
      type: 'color',
    },
    name: 'semantic_surface_tertiary_light_active',
    attributes: {},
    path: ['semantic', 'surface', 'tertiary', 'light-active'],
  },
  {
    value: '#5A121D',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{brand.tertiary.800}',
      type: 'color',
    },
    name: 'semantic_surface_tertiary_dark',
    attributes: {},
    path: ['semantic', 'surface', 'tertiary', 'dark'],
  },
  {
    value: '#ffffff',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '#ffffff',
      type: 'color',
    },
    name: 'semantic_surface_on_inverted_default',
    attributes: {},
    path: ['semantic', 'surface', 'on_inverted', 'default'],
  },
  {
    value: '#ffffffe6',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '#ffffffe6',
      type: 'color',
    },
    name: 'semantic_surface_on_inverted_hover',
    attributes: {},
    path: ['semantic', 'surface', 'on_inverted', 'hover'],
  },
  {
    value: '#ffffffcc',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '#ffffffcc',
      type: 'color',
    },
    name: 'semantic_surface_on_inverted_active',
    attributes: {},
    path: ['semantic', 'surface', 'on_inverted', 'active'],
  },
  {
    value: '#ffffff00',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '#ffffff00',
      type: 'color',
    },
    name: 'semantic_surface_on_inverted_no_fill',
    attributes: {},
    path: ['semantic', 'surface', 'on_inverted', 'no_fill'],
  },
  {
    value: '#ffffff1a',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '#ffffff1a',
      type: 'color',
    },
    name: 'semantic_surface_on_inverted_no_fill_hover',
    attributes: {},
    path: ['semantic', 'surface', 'on_inverted', 'no_fill-hover'],
  },
  {
    value: '#ffffff33',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '#ffffff33',
      type: 'color',
    },
    name: 'semantic_surface_on_inverted_no_fill_active',
    attributes: {},
    path: ['semantic', 'surface', 'on_inverted', 'no_fill-active'],
  },
  {
    value: '#ffffff',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.white}',
      type: 'color',
    },
    name: 'semantic_background_default',
    attributes: {},
    path: ['semantic', 'background', 'default'],
  },
  {
    value: '#f4f5f6',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.100}',
      type: 'color',
    },
    name: 'semantic_background_subtle',
    attributes: {},
    path: ['semantic', 'background', 'subtle'],
  },
  {
    value: '#004e95',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.800}',
      type: 'color',
    },
    name: 'semantic_border_info_default',
    attributes: {},
    path: ['semantic', 'border', 'info', 'default'],
  },
  {
    value: '#b3d0ea',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.200}',
      type: 'color',
    },
    name: 'semantic_border_action_primary_subtle',
    attributes: {},
    path: ['semantic', 'border', 'action', 'primary', 'subtle'],
  },
  {
    value: '#66a1d6',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.400}',
      type: 'color',
    },
    name: 'semantic_border_action_primary_subtle_hover',
    attributes: {},
    path: ['semantic', 'border', 'action', 'primary', 'subtle-hover'],
  },
  {
    value: '#0062ba',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.700}',
      type: 'color',
    },
    name: 'semantic_border_action_primary_default',
    attributes: {},
    path: ['semantic', 'border', 'action', 'primary', 'default'],
  },
  {
    value: '#004e95',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.800}',
      type: 'color',
    },
    name: 'semantic_border_action_primary_hover',
    attributes: {},
    path: ['semantic', 'border', 'action', 'primary', 'hover'],
  },
  {
    value: '#00315d',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.900}',
      type: 'color',
    },
    name: 'semantic_border_action_primary_active',
    attributes: {},
    path: ['semantic', 'border', 'action', 'primary', 'active'],
  },
  {
    value: '#e9eaec',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.200}',
      type: 'color',
    },
    name: 'semantic_border_action_secondary_subtle',
    attributes: {},
    path: ['semantic', 'border', 'action', 'secondary', 'subtle'],
  },
  {
    value: '#d2d5d8',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.300}',
      type: 'color',
    },
    name: 'semantic_border_action_secondary_subtle_hover',
    attributes: {},
    path: ['semantic', 'border', 'action', 'secondary', 'subtle-hover'],
  },
  {
    value: '#00315d',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.900}',
      type: 'color',
    },
    name: 'semantic_border_action_secondary_default',
    attributes: {},
    path: ['semantic', 'border', 'action', 'secondary', 'default'],
  },
  {
    value: '#00315d',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.900}',
      type: 'color',
    },
    name: 'semantic_border_action_secondary_hover',
    attributes: {},
    path: ['semantic', 'border', 'action', 'secondary', 'hover'],
  },
  {
    value: '#00315d',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.900}',
      type: 'color',
    },
    name: 'semantic_border_action_secondary_active',
    attributes: {},
    path: ['semantic', 'border', 'action', 'secondary', 'active'],
  },
  {
    value: '#68707c',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.600}',
      type: 'color',
    },
    name: 'semantic_border_neutral_default',
    attributes: {},
    path: ['semantic', 'border', 'neutral', 'default'],
  },
  {
    value: '#d2d5d8',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.300}',
      type: 'color',
    },
    name: 'semantic_border_neutral_subtle',
    attributes: {},
    path: ['semantic', 'border', 'neutral', 'subtle'],
  },
  {
    value: '#1e2b3c',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.800}',
      type: 'color',
    },
    name: 'semantic_border_neutral_strong',
    attributes: {},
    path: ['semantic', 'border', 'neutral', 'strong'],
  },
  {
    value: '#bcbfc5',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.400}',
      type: 'color',
    },
    name: 'semantic_border_neutral_divider',
    attributes: {},
    path: ['semantic', 'border', 'neutral', 'divider'],
  },
  {
    value: '#118849',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.green.700}',
      type: 'color',
    },
    name: 'semantic_border_success_default',
    attributes: {},
    path: ['semantic', 'border', 'success', 'default'],
  },
  {
    value: '#0c6536',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.green.800}',
      type: 'color',
    },
    name: 'semantic_border_success_hover',
    attributes: {},
    path: ['semantic', 'border', 'success', 'hover'],
  },
  {
    value: '#084826',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.green.900}',
      type: 'color',
    },
    name: 'semantic_border_success_active',
    attributes: {},
    path: ['semantic', 'border', 'success', 'active'],
  },
  {
    value: '#cc7005',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.orange.600}',
      type: 'color',
    },
    name: 'semantic_border_warning_default',
    attributes: {},
    path: ['semantic', 'border', 'warning', 'default'],
  },
  {
    value: '#995404',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.orange.700}',
      type: 'color',
    },
    name: 'semantic_border_warning_hover',
    attributes: {},
    path: ['semantic', 'border', 'warning', 'hover'],
  },
  {
    value: '#663802',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.orange.800}',
      type: 'color',
    },
    name: 'semantic_border_warning_active',
    attributes: {},
    path: ['semantic', 'border', 'warning', 'active'],
  },
  {
    value: '#e02e49',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.red.500}',
      type: 'color',
    },
    name: 'semantic_border_danger_default',
    attributes: {},
    path: ['semantic', 'border', 'danger', 'default'],
  },
  {
    value: '#b3253a',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.red.600}',
      type: 'color',
    },
    name: 'semantic_border_danger_hover',
    attributes: {},
    path: ['semantic', 'border', 'danger', 'hover'],
  },
  {
    value: '#861c2c',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.red.700}',
      type: 'color',
    },
    name: 'semantic_border_danger_active',
    attributes: {},
    path: ['semantic', 'border', 'danger', 'active'],
  },
  {
    value: '#ffda06',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.yellow.500}',
      type: 'color',
    },
    name: 'semantic_border_focus_outline',
    attributes: {},
    path: ['semantic', 'border', 'focus', 'outline'],
  },
  {
    value: '#1e2b3c',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{semantic.border.neutral.strong}',
      type: 'color',
    },
    name: 'semantic_border_focus_boxshadow',
    attributes: {},
    path: ['semantic', 'border', 'focus', 'boxshadow'],
  },
  {
    value: '#1A72C1',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{brand.primary.600}',
      type: 'color',
    },
    name: 'semantic_border_primary_default',
    attributes: {},
    path: ['semantic', 'border', 'primary', 'default'],
  },
  {
    value: '#0062BA',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{brand.primary.700}',
      type: 'color',
    },
    name: 'semantic_border_primary_hover',
    attributes: {},
    path: ['semantic', 'border', 'primary', 'hover'],
  },
  {
    value: '#004E95',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{brand.primary.800}',
      type: 'color',
    },
    name: 'semantic_border_primary_active',
    attributes: {},
    path: ['semantic', 'border', 'primary', 'active'],
  },
  {
    value: '#594488',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{brand.secondary.600}',
      type: 'color',
    },
    name: 'semantic_border_secondary_default',
    attributes: {},
    path: ['semantic', 'border', 'secondary', 'default'],
  },
  {
    value: '#3F3161',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{brand.secondary.700}',
      type: 'color',
    },
    name: 'semantic_border_secondary_hover',
    attributes: {},
    path: ['semantic', 'border', 'secondary', 'hover'],
  },
  {
    value: '#352951',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{brand.secondary.800}',
      type: 'color',
    },
    name: 'semantic_border_secondary_active',
    attributes: {},
    path: ['semantic', 'border', 'secondary', 'active'],
  },
  {
    value: '#B3253A',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{brand.tertiary.600}',
      type: 'color',
    },
    name: 'semantic_border_tertiary_default',
    attributes: {},
    path: ['semantic', 'border', 'tertiary', 'default'],
  },
  {
    value: '#861C2C',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{brand.tertiary.700}',
      type: 'color',
    },
    name: 'semantic_border_tertiary_hover',
    attributes: {},
    path: ['semantic', 'border', 'tertiary', 'hover'],
  },
  {
    value: '#5A121D',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{brand.tertiary.800}',
      type: 'color',
    },
    name: 'semantic_border_tertiary_active',
    attributes: {},
    path: ['semantic', 'border', 'tertiary', 'active'],
  },
  {
    value: '#ffffff',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '#ffffff',
      type: 'color',
    },
    name: 'semantic_border_on_inverted_default',
    attributes: {},
    path: ['semantic', 'border', 'on_inverted', 'default'],
  },
  {
    value: '#00315d',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '#00315d',
      type: 'color',
    },
    name: 'semantic_border_input_default',
    attributes: {},
    path: ['semantic', 'border', 'input', 'default'],
  },
  {
    value: '#0062ba',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '#0062ba',
      type: 'color',
    },
    name: 'semantic_border_input_hover',
    attributes: {},
    path: ['semantic', 'border', 'input', 'hover'],
  },
  {
    value: '#0c6536',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.green.800}',
      type: 'color',
    },
    name: 'semantic_text_success_default',
    attributes: {},
    path: ['semantic', 'text', 'success', 'default'],
  },
  {
    value: '#084826',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '#084826',
      type: 'color',
    },
    name: 'semantic_text_success_hover',
    attributes: {},
    path: ['semantic', 'text', 'success', 'hover'],
  },
  {
    value: '#084826',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '#084826',
      type: 'color',
    },
    name: 'semantic_text_success_active',
    attributes: {},
    path: ['semantic', 'text', 'success', 'active'],
  },
  {
    value: '#ffffff',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.white}',
      type: 'color',
    },
    name: 'semantic_text_success_on_success',
    attributes: {},
    path: ['semantic', 'text', 'success', 'on_success'],
  },
  {
    value: '#1e2b3c',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '#1e2b3c',
      type: 'color',
    },
    name: 'semantic_text_success_on_success_subtle',
    attributes: {},
    path: ['semantic', 'text', 'success', 'on_success_subtle'],
  },
  {
    value: '#1e2b3c',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.800}',
      type: 'color',
    },
    name: 'semantic_text_neutral_default',
    attributes: {},
    path: ['semantic', 'text', 'neutral', 'default'],
  },
  {
    value: '#4b5563',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.700}',
      type: 'color',
    },
    name: 'semantic_text_neutral_subtle',
    attributes: {},
    path: ['semantic', 'text', 'neutral', 'subtle'],
  },
  {
    value: '#ffffff',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.white}',
      type: 'color',
    },
    name: 'semantic_text_neutral_on_inverted',
    attributes: {},
    path: ['semantic', 'text', 'neutral', 'on_inverted'],
  },
  {
    value: '#0062ba',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.700}',
      type: 'color',
    },
    name: 'semantic_text_action_primary_default',
    attributes: {},
    path: ['semantic', 'text', 'action', 'primary', 'default'],
  },
  {
    value: '#004e95',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '#004e95',
      type: 'color',
    },
    name: 'semantic_text_action_primary_hover',
    attributes: {},
    path: ['semantic', 'text', 'action', 'primary', 'hover'],
  },
  {
    value: '#00315d',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '#00315d',
      type: 'color',
    },
    name: 'semantic_text_action_primary_active',
    attributes: {},
    path: ['semantic', 'text', 'action', 'primary', 'active'],
  },
  {
    value: '#ffffff',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.white}',
      type: 'color',
    },
    name: 'semantic_text_action_primary_on_action',
    attributes: {},
    path: ['semantic', 'text', 'action', 'primary', 'on_action'],
  },
  {
    value: '#00315d',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.900}',
      type: 'color',
    },
    name: 'semantic_text_action_secondary_default',
    attributes: {},
    path: ['semantic', 'text', 'action', 'secondary', 'default'],
  },
  {
    value: '#00315d',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.900}',
      type: 'color',
    },
    name: 'semantic_text_action_secondary_hover',
    attributes: {},
    path: ['semantic', 'text', 'action', 'secondary', 'hover'],
  },
  {
    value: '#00315d',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.900}',
      type: 'color',
    },
    name: 'semantic_text_action_secondary_active',
    attributes: {},
    path: ['semantic', 'text', 'action', 'secondary', 'active'],
  },
  {
    value: '#ffffff',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.white}',
      type: 'color',
    },
    name: 'semantic_text_action_secondary_on_action',
    attributes: {},
    path: ['semantic', 'text', 'action', 'secondary', 'on_action'],
  },
  {
    value: '#995404',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.orange.700}',
      type: 'color',
    },
    name: 'semantic_text_warning_default',
    attributes: {},
    path: ['semantic', 'text', 'warning', 'default'],
  },
  {
    value: '#cc7005',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.orange.600}',
      type: 'color',
    },
    name: 'semantic_text_warning_icon_warning',
    attributes: {},
    path: ['semantic', 'text', 'warning', 'icon_warning'],
  },
  {
    value: '#663802',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.orange.800}',
      type: 'color',
    },
    name: 'semantic_text_warning_on_warning',
    attributes: {},
    path: ['semantic', 'text', 'warning', 'on_warning'],
  },
  {
    value: '#b3253a',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.red.600}',
      type: 'color',
    },
    name: 'semantic_text_danger_default',
    attributes: {},
    path: ['semantic', 'text', 'danger', 'default'],
  },
  {
    value: '#861c2c',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '#861c2c',
      type: 'color',
    },
    name: 'semantic_text_danger_hover',
    attributes: {},
    path: ['semantic', 'text', 'danger', 'hover'],
  },
  {
    value: '#5a121d',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '#5a121d',
      type: 'color',
    },
    name: 'semantic_text_danger_active',
    attributes: {},
    path: ['semantic', 'text', 'danger', 'active'],
  },
  {
    value: '#ffffff',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.white}',
      type: 'color',
    },
    name: 'semantic_text_danger_on_danger',
    attributes: {},
    path: ['semantic', 'text', 'danger', 'on_danger'],
  },
  {
    value: '#1e2b3c',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '#1e2b3c',
      type: 'color',
    },
    name: 'semantic_text_danger_on_danger_subtle',
    attributes: {},
    path: ['semantic', 'text', 'danger', 'on_danger_subtle'],
  },
  {
    value: '#7a1265',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.purple.700}',
      type: 'color',
    },
    name: 'semantic_text_visited_default',
    attributes: {},
    path: ['semantic', 'text', 'visited', 'default'],
  },
];
export const typography = [
  {
    value: "500 2.34375rem/1.3 'Inter'",
    type: 'typography',
    description: 'H1',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.medium}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f5}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
      description: 'H1',
    },
    name: 'typography_heading_xlarge',
    attributes: {},
    path: ['typography', 'heading', 'xlarge'],
  },
  {
    value: "500 2rem/1.3 'Inter'",
    type: 'typography',
    description: 'H2',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.medium}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f4}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
      description: 'H2',
    },
    name: 'typography_heading_large',
    attributes: {},
    path: ['typography', 'heading', 'large'],
  },
  {
    value: "500 1.75rem/1.3 'Inter'",
    type: 'typography',
    description: 'H3',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.medium}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f3}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
      description: 'H3',
    },
    name: 'typography_heading_medium',
    attributes: {},
    path: ['typography', 'heading', 'medium'],
  },
  {
    value: "500 1.5rem/1.3 'Inter'",
    type: 'typography',
    description: 'H4',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.medium}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f2}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
      description: 'H4',
    },
    name: 'typography_heading_small',
    attributes: {},
    path: ['typography', 'heading', 'small'],
  },
  {
    value: "500 1.3125rem/1.3 'Inter'",
    type: 'typography',
    description: 'H5',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.medium}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f1}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
      description: 'H5',
    },
    name: 'typography_heading_xsmall',
    attributes: {},
    path: ['typography', 'heading', 'xsmall'],
  },
  {
    value: "500 1.125rem/1.3 'Inter'",
    type: 'typography',
    description: 'H6',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.medium}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f0}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
      description: 'H6',
    },
    name: 'typography_heading_xxsmall',
    attributes: {},
    path: ['typography', 'heading', 'xxsmall'],
  },
  {
    value: "400 1.3125rem/1.6 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.600}',
        fontSize: '{font-size.f1}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
    },
    name: 'typography_ingress_medium',
    attributes: {},
    path: ['typography', 'ingress', 'medium'],
  },
  {
    value: "400 1.3125rem/1.5 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.500}',
        fontSize: '{font-size.f1}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
    },
    name: 'typography_paragraph_large',
    attributes: {},
    path: ['typography', 'paragraph', 'large'],
  },
  {
    value: "400 1.125rem/1.5 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.500}',
        fontSize: '{font-size.f0}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
    },
    name: 'typography_paragraph_medium',
    attributes: {},
    path: ['typography', 'paragraph', 'medium'],
  },
  {
    value: "400 0.9375rem/1.5 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.500}',
        fontSize: '{font-size.f-1}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
    },
    name: 'typography_paragraph_small',
    attributes: {},
    path: ['typography', 'paragraph', 'small'],
  },
  {
    value: "400 0.8125rem/1.5 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.500}',
        fontSize: '{font-size.f-2}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
    },
    name: 'typography_paragraph_xsmall',
    attributes: {},
    path: ['typography', 'paragraph', 'xsmall'],
  },
  {
    value: "400 1.3125rem/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f1}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
    },
    name: 'typography_paragraph_short_large',
    attributes: {},
    path: ['typography', 'paragraph', 'short', 'large'],
  },
  {
    value: "400 1.125rem/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f0}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
    },
    name: 'typography_paragraph_short_medium',
    attributes: {},
    path: ['typography', 'paragraph', 'short', 'medium'],
  },
  {
    value: "400 0.9375rem/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f-1}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
    },
    name: 'typography_paragraph_short_small',
    attributes: {},
    path: ['typography', 'paragraph', 'short', 'small'],
  },
  {
    value: "400 0.8125rem/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f-2}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
    },
    name: 'typography_paragraph_short_xsmall',
    attributes: {},
    path: ['typography', 'paragraph', 'short', 'xsmall'],
  },
  {
    value: "500 1.3125rem/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.medium}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f1}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
    },
    name: 'typography_label_large',
    attributes: {},
    path: ['typography', 'label', 'large'],
  },
  {
    value: "500 1.125rem/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.medium}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f0}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
    },
    name: 'typography_label_medium',
    attributes: {},
    path: ['typography', 'label', 'medium'],
  },
  {
    value: "500 0.9375rem/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.medium}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f-1}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
    },
    name: 'typography_label_small',
    attributes: {},
    path: ['typography', 'label', 'small'],
  },
  {
    value: "500 0.8125rem/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.medium}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f-2}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
    },
    name: 'typography_label_xsmall',
    attributes: {},
    path: ['typography', 'label', 'xsmall'],
  },
  {
    value: "400 1.3125rem/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f1}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
    },
    name: 'typography_label_radio_and_checkbox_large',
    attributes: {},
    path: ['typography', 'label', 'radio_and_checkbox', 'large'],
  },
  {
    value: "400 1.125rem/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f0}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
    },
    name: 'typography_label_radio_and_checkbox_medium',
    attributes: {},
    path: ['typography', 'label', 'radio_and_checkbox', 'medium'],
  },
  {
    value: "400 0.9375rem/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f-1}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
    },
    name: 'typography_label_radio_and_checkbox_small',
    attributes: {},
    path: ['typography', 'label', 'radio_and_checkbox', 'small'],
  },
  {
    value: "400 0.8125rem/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f-2}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
    },
    name: 'typography_label_radio_and_checkbox_xsmall',
    attributes: {},
    path: ['typography', 'label', 'radio_and_checkbox', 'xsmall'],
  },
  {
    value: "400 1.125rem/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f0}',
        letterSpacing: '{letterSpacing.1}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
    },
    name: 'typography_error_message_medium',
    attributes: {},
    path: ['typography', 'error_message', 'medium'],
  },
  {
    value: "400 0.9375rem/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f-1}',
        letterSpacing: '{letterSpacing.1}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
    },
    name: 'typography_error_message_small',
    attributes: {},
    path: ['typography', 'error_message', 'small'],
  },
  {
    value: "400 0.8125rem/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f-2}',
        letterSpacing: '{letterSpacing.1}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
    },
    name: 'typography_error_message_xsmall',
    attributes: {},
    path: ['typography', 'error_message', 'xsmall'],
  },
  {
    value: "400 1.5rem/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-static.large}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
    },
    name: 'typography_interactive_large',
    attributes: {},
    path: ['typography', 'interactive', 'large'],
  },
  {
    value: "400 1.125rem/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-static.medium}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
    },
    name: 'typography_interactive_medium',
    attributes: {},
    path: ['typography', 'interactive', 'medium'],
  },
  {
    value: "400 1rem/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-static.small}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      type: 'typography',
    },
    name: 'typography_interactive_small',
    attributes: {},
    path: ['typography', 'interactive', 'small'],
  },
];
export const opacity = [
  {
    value: '30%',
    type: 'opacity',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '30%',
      type: 'opacity',
    },
    name: 'opacity_disabled',
    attributes: {},
    path: ['opacity', 'disabled'],
  },
];
export const borderRadius = [
  {
    value: '4px',
    type: 'borderRadius',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{border_radius.medium}',
      type: 'borderRadius',
    },
    name: 'border_radius_interactive',
    attributes: {},
    path: ['border_radius', 'interactive'],
  },
  {
    value: '2px',
    type: 'borderRadius',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '2px',
      type: 'borderRadius',
    },
    name: 'border_radius_small',
    attributes: {},
    path: ['border_radius', 'small'],
  },
  {
    value: '4px',
    type: 'borderRadius',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '4px',
      type: 'borderRadius',
    },
    name: 'border_radius_medium',
    attributes: {},
    path: ['border_radius', 'medium'],
  },
  {
    value: '8px',
    type: 'borderRadius',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '8px',
      type: 'borderRadius',
    },
    name: 'border_radius_large',
    attributes: {},
    path: ['border_radius', 'large'],
  },
  {
    value: '12px',
    type: 'borderRadius',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '12px',
      type: 'borderRadius',
    },
    name: 'border_radius_xlarge',
    attributes: {},
    path: ['border_radius', 'xlarge'],
  },
  {
    value: '9999px',
    type: 'borderRadius',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '9999px',
      type: 'borderRadius',
    },
    name: 'border_radius_full',
    attributes: {},
    path: ['border_radius', 'full'],
  },
];
export const spacing = [
  {
    value: '0',
    type: 'spacing',
    description: '0',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '0',
      type: 'spacing',
      description: '0',
    },
    name: 'spacing_0',
    attributes: {},
    path: ['spacing', '0'],
  },
  {
    value: '4.5px',
    type: 'spacing',
    description: '4px - 4.5px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_spacing}/16*{font-size.f0}',
      type: 'spacing',
      description: '4px - 4.5px',
    },
    name: 'spacing_1',
    attributes: {},
    path: ['spacing', '1'],
  },
  {
    value: '9px',
    type: 'spacing',
    description: '8px - 9px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_spacing}*2/16*{font-size.f0}',
      type: 'spacing',
      description: '8px - 9px',
    },
    name: 'spacing_2',
    attributes: {},
    path: ['spacing', '2'],
  },
  {
    value: '13.5px',
    type: 'spacing',
    description: '12px - 13.5px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_spacing}*3/16*{font-size.f0}',
      type: 'spacing',
      description: '12px - 13.5px',
    },
    name: 'spacing_3',
    attributes: {},
    path: ['spacing', '3'],
  },
  {
    value: '18px',
    type: 'spacing',
    description: '16px - 18px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_spacing}*4/16*{font-size.f0}',
      type: 'spacing',
      description: '16px - 18px',
    },
    name: 'spacing_4',
    attributes: {},
    path: ['spacing', '4'],
  },
  {
    value: '22.5px',
    type: 'spacing',
    description: '20px - 22.5px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_spacing}*5/16*{font-size.f0}',
      type: 'spacing',
      description: '20px - 22.5px',
    },
    name: 'spacing_5',
    attributes: {},
    path: ['spacing', '5'],
  },
  {
    value: '27px',
    type: 'spacing',
    description: '24px - 27px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_spacing}*6/16*{font-size.f0}',
      type: 'spacing',
      description: '24px - 27px',
    },
    name: 'spacing_6',
    attributes: {},
    path: ['spacing', '6'],
  },
  {
    value: '31.5px',
    type: 'spacing',
    description: '28px - 31.5px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_spacing}*7/16*{font-size.f0}',
      type: 'spacing',
      description: '28px - 31.5px',
    },
    name: 'spacing_7',
    attributes: {},
    path: ['spacing', '7'],
  },
  {
    value: '36px',
    type: 'spacing',
    description: '32px - 36px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '({base_spacing}*8/16)*{font-size.f0}',
      type: 'spacing',
      description: '32px - 36px',
    },
    name: 'spacing_8',
    attributes: {},
    path: ['spacing', '8'],
  },
  {
    value: '45px',
    type: 'spacing',
    description: '40px - 45px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '({base_spacing}*10/16)*{font-size.f0}',
      type: 'spacing',
      description: '40px - 45px',
    },
    name: 'spacing_10',
    attributes: {},
    path: ['spacing', '10'],
  },
  {
    value: '54px',
    type: 'spacing',
    description: '48px - 54px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '({base_spacing}*12/16)*{font-size.f0}',
      type: 'spacing',
      description: '48px - 54px',
    },
    name: 'spacing_12',
    attributes: {},
    path: ['spacing', '12'],
  },
  {
    value: '63px',
    type: 'spacing',
    description: '56px - 63px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '({base_spacing}*14/16)*{font-size.f0}',
      type: 'spacing',
      description: '56px - 63px',
    },
    name: 'spacing_14',
    attributes: {},
    path: ['spacing', '14'],
  },
  {
    value: '81px',
    type: 'spacing',
    description: '72px - 81px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '({base_spacing}*18/16)*{font-size.f0}',
      type: 'spacing',
      description: '72px - 81px',
    },
    name: 'spacing_18',
    attributes: {},
    path: ['spacing', '18'],
  },
  {
    value: '99px',
    type: 'spacing',
    description: '88px - 99px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '({base_spacing}*22/16)*{font-size.f0}',
      type: 'spacing',
      description: '88px - 99px',
    },
    name: 'spacing_22',
    attributes: {},
    path: ['spacing', '22'],
  },
  {
    value: '117px',
    type: 'spacing',
    description: '104px - 117px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '({base_spacing}*26/16)*{font-size.f0}',
      type: 'spacing',
      description: '104px - 117px',
    },
    name: 'spacing_26',
    attributes: {},
    path: ['spacing', '26'],
  },
  {
    value: '135px',
    type: 'spacing',
    description: '120px - 135px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '({base_spacing}*30/16)*{font-size.f0}',
      type: 'spacing',
      description: '120px - 135px',
    },
    name: 'spacing_30',
    attributes: {},
    path: ['spacing', '30'],
  },
  {
    value: '4px',
    type: 'spacing',
    description: '4px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '4',
      type: 'spacing',
      description: '4px',
    },
    name: 'base_spacing',
    attributes: {},
    path: ['base_spacing'],
  },
  {
    value: '9px',
    type: 'spacing',
    filePath: '../../design-tokens/Density/Default.json',
    isSource: false,
    original: {
      value: '{spacing.2}',
      type: 'spacing',
    },
    name: 'component_mode_spacing_small',
    attributes: {},
    path: ['component-mode-spacing', 'small'],
  },
  {
    value: '13.5px',
    type: 'spacing',
    filePath: '../../design-tokens/Density/Default.json',
    isSource: false,
    original: {
      value: '{spacing.3}',
      type: 'spacing',
    },
    name: 'component_mode_spacing_medium',
    attributes: {},
    path: ['component-mode-spacing', 'medium'],
  },
  {
    value: '18px',
    type: 'spacing',
    filePath: '../../design-tokens/Density/Default.json',
    isSource: false,
    original: {
      value: '{spacing.4}',
      type: 'spacing',
    },
    name: 'component_mode_spacing_large',
    attributes: {},
    path: ['component-mode-spacing', 'large'],
  },
  {
    value: '4.5px',
    type: 'spacing',
    filePath: '../../design-tokens/Density/Default.json',
    isSource: false,
    original: {
      value: '{spacing.1}',
      type: 'spacing',
    },
    name: 'component_mode_gap_small',
    attributes: {},
    path: ['component-mode-gap', 'small'],
  },
  {
    value: '9px',
    type: 'spacing',
    filePath: '../../design-tokens/Density/Default.json',
    isSource: false,
    original: {
      value: '{spacing.2}',
      type: 'spacing',
    },
    name: 'component_mode_gap_medium',
    attributes: {},
    path: ['component-mode-gap', 'medium'],
  },
  {
    value: '13.5px',
    type: 'spacing',
    filePath: '../../design-tokens/Density/Default.json',
    isSource: false,
    original: {
      value: '{spacing.3}',
      type: 'spacing',
    },
    name: 'component_mode_gap_large',
    attributes: {},
    path: ['component-mode-gap', 'large'],
  },
];
export const sizing = [
  {
    value: '4.5px',
    type: 'sizing',
    description: '4px - 4.5px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_sizing}/16*{font-size.f0}',
      type: 'sizing',
      description: '4px - 4.5px',
    },
    name: 'sizing_1',
    attributes: {},
    path: ['sizing', '1'],
  },
  {
    value: '9px',
    type: 'sizing',
    description: '8px - 9px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_sizing}*2/16*{font-size.f0}',
      type: 'sizing',
      description: '8px - 9px',
    },
    name: 'sizing_2',
    attributes: {},
    path: ['sizing', '2'],
  },
  {
    value: '13.5px',
    type: 'sizing',
    description: '12px - 13.5px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_sizing}*3/16*{font-size.f0}',
      type: 'sizing',
      description: '12px - 13.5px',
    },
    name: 'sizing_3',
    attributes: {},
    path: ['sizing', '3'],
  },
  {
    value: '18px',
    type: 'sizing',
    description: '16px - 18px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_sizing}*4/16*{font-size.f0}',
      type: 'sizing',
      description: '16px - 18px',
    },
    name: 'sizing_4',
    attributes: {},
    path: ['sizing', '4'],
  },
  {
    value: '22.5px',
    type: 'sizing',
    description: '20px - 22.5',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_sizing}*5/16*{font-size.f0}',
      type: 'sizing',
      description: '20px - 22.5',
    },
    name: 'sizing_5',
    attributes: {},
    path: ['sizing', '5'],
  },
  {
    value: '27px',
    type: 'sizing',
    description: '24px - 27px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_sizing}*6/16*{font-size.f0}',
      type: 'sizing',
      description: '24px - 27px',
    },
    name: 'sizing_6',
    attributes: {},
    path: ['sizing', '6'],
  },
  {
    value: '31.5px',
    type: 'sizing',
    description: '28px - 31.5px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_sizing}*7/16*{font-size.f0}',
      type: 'sizing',
      description: '28px - 31.5px',
    },
    name: 'sizing_7',
    attributes: {},
    path: ['sizing', '7'],
  },
  {
    value: '36px',
    type: 'sizing',
    description: '32px - 36px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_sizing}*8/16*{font-size.f0}',
      type: 'sizing',
      description: '32px - 36px',
    },
    name: 'sizing_8',
    attributes: {},
    path: ['sizing', '8'],
  },
  {
    value: '45px',
    type: 'sizing',
    description: '40px - 45px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_sizing}*10/16*{font-size.f0}',
      type: 'sizing',
      description: '40px - 45px',
    },
    name: 'sizing_10',
    attributes: {},
    path: ['sizing', '10'],
  },
  {
    value: '54px',
    type: 'sizing',
    description: '48px - 54px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '({base_sizing}*12/16)*{font-size.f0}',
      type: 'sizing',
      description: '48px - 54px',
    },
    name: 'sizing_12',
    attributes: {},
    path: ['sizing', '12'],
  },
  {
    value: '63px',
    type: 'sizing',
    description: '56px - 63px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '({base_sizing}*14/16)*{font-size.f0}',
      type: 'sizing',
      description: '56px - 63px',
    },
    name: 'sizing_14',
    attributes: {},
    path: ['sizing', '14'],
  },
  {
    value: '81px',
    type: 'sizing',
    description: '72px - 81px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '({base_sizing}*18/16)*{font-size.f0}',
      type: 'sizing',
      description: '72px - 81px',
    },
    name: 'sizing_18',
    attributes: {},
    path: ['sizing', '18'],
  },
  {
    value: '99px',
    type: 'sizing',
    description: '88px - 99px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '({base_sizing}*22/16)*{font-size.f0}',
      type: 'sizing',
      description: '88px - 99px',
    },
    name: 'sizing_22',
    attributes: {},
    path: ['sizing', '22'],
  },
  {
    value: '117px',
    type: 'sizing',
    description: '104px - 117px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '({base_sizing}*26/16)*{font-size.f0}',
      type: 'sizing',
      description: '104px - 117px',
    },
    name: 'sizing_26',
    attributes: {},
    path: ['sizing', '26'],
  },
  {
    value: '135px',
    type: 'sizing',
    description: '120px - 135px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '({base_sizing}*30/16)*{font-size.f0}',
      type: 'sizing',
      description: '120px - 135px',
    },
    name: 'sizing_30',
    attributes: {},
    path: ['sizing', '30'],
  },
  {
    value: '4px',
    type: 'sizing',
    description: '4px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '4',
      type: 'sizing',
      description: '4px',
    },
    name: 'base_sizing',
    attributes: {},
    path: ['base_sizing'],
  },
  {
    value: '36px',
    type: 'sizing',
    filePath: '../../design-tokens/Density/Default.json',
    isSource: false,
    original: {
      value: '36',
      type: 'sizing',
    },
    name: 'component_mode_height_small',
    attributes: {},
    path: ['component-mode-height', 'small'],
  },
  {
    value: '45px',
    type: 'sizing',
    filePath: '../../design-tokens/Density/Default.json',
    isSource: false,
    original: {
      value: '{sizing.10}',
      type: 'sizing',
    },
    name: 'component_mode_height_medium',
    attributes: {},
    path: ['component-mode-height', 'medium'],
  },
  {
    value: '54px',
    type: 'sizing',
    filePath: '../../design-tokens/Density/Default.json',
    isSource: false,
    original: {
      value: '{sizing.12}',
      type: 'sizing',
    },
    name: 'component_mode_height_large',
    attributes: {},
    path: ['component-mode-height', 'large'],
  },
];
export const borderWidth = [
  {
    value: '1px',
    type: 'borderWidth',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{border_width.1}',
      type: 'borderWidth',
    },
    name: 'border_width_default',
    attributes: {},
    path: ['border_width', 'default'],
  },
  {
    value: '2px',
    type: 'borderWidth',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{border_width.2}',
      type: 'borderWidth',
    },
    name: 'border_width_active',
    attributes: {},
    path: ['border_width', 'active'],
  },
  {
    value: '2px',
    type: 'borderWidth',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '2px',
      type: 'borderWidth',
    },
    name: 'border_width_tab_focus',
    attributes: {},
    path: ['border_width', 'tab_focus'],
  },
];
export const boxShadow = [
  {
    value: '0 1px 2px 0 #0000001f',
    type: 'boxShadow',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{shadow.100}',
      type: 'boxShadow',
    },
    name: 'shadow_xsmall',
    attributes: {},
    path: ['shadow', 'xsmall'],
  },
  {
    value: '0 1px 2px -1px #0000001a, 0 1px 4px 0 #0000001a',
    type: 'boxShadow',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{shadow.200}',
      type: 'boxShadow',
    },
    name: 'shadow_small',
    attributes: {},
    path: ['shadow', 'small'],
  },
  {
    value: '0 2px 4px -2px #0000001a, 0 4px 5px #0000001a',
    type: 'boxShadow',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{shadow.300}',
      type: 'boxShadow',
    },
    name: 'shadow_medium',
    attributes: {},
    path: ['shadow', 'medium'],
  },
  {
    value: '0 4px 6px -4px #0000001a, 0 10px 12px #0000001a',
    type: 'boxShadow',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{shadow.400}',
      type: 'boxShadow',
    },
    name: 'shadow_large',
    attributes: {},
    path: ['shadow', 'large'],
  },
  {
    value: '0 8px 10px -6px #0000001a, 0 25px 45px #0000001a',
    type: 'boxShadow',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{shadow.500}',
      type: 'boxShadow',
    },
    name: 'shadow_xlarge',
    attributes: {},
    path: ['shadow', 'xlarge'],
  },
];
