import 'normalize.css/normalize.css';
import '@altinn/figma-design-tokens/dist/tokens.css';
import '@digdir/designsystemet-theme/brand/digdir/tokens.css';
import '../globals.css';

import { draftMode } from 'next/headers';

import LiveVisualEditing from '../components/LiveVisualEditing/LiveVisualEditing';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='no'>
      <body>
        {children}
        {draftMode().isEnabled && <LiveVisualEditing />}
      </body>
    </html>
  );
}
