name: Setup GH
description: Setup GitHub Actions
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 10.10.0
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
