export const luminance = {
  light: {
    backgroundDefault: 1,
    backgroundSubtle: 0.9,
    surfaceDefault: 0.76,
    surfaceHover: 0.64,
    surfaceActive: 0.54,
    borderSubtle: 0.5,
    borderDefault: 0.21,
    borderStrong: 0.12,
    baseDefault: 1,
    baseHover: 1,
    baseActive: 1,
    textSubtle: 0.12,
    textDefault: 0.0245,
    baseContrastDefault: 1,
    baseContrastSubtle: 1,
  },
  dark: {
    backgroundDefault: 0.012,
    backgroundSubtle: 0.018,
    surfaceDefault: 0.029,
    surfaceHover: 0.046,
    surfaceActive: 0.069,
    borderSubtle: 0.082,
    borderDefault: 0.2,
    borderStrong: 0.36,
    baseDefault: 1,
    baseHover: 1,
    baseActive: 1,
    textSubtle: 0.36,
    textDefault: 0.78,
    baseContrastDefault: 1,
    baseContrastSubtle: 1,
  },
  contrast: {
    backgroundDefault: 0.001,
    backgroundSubtle: 0.0065,
    surfaceDefault: 0.015,
    surfaceHover: 0.028,
    surfaceActive: 0.044,
    borderSubtle: 0.26,
    borderDefault: 0.4,
    borderStrong: 0.6,
    baseDefault: 1,
    baseHover: 1,
    baseActive: 1,
    textSubtle: 0.57,
    textDefault: 0.86,
    baseContrastDefault: 1,
    baseContrastSubtle: 1,
  },
};
