export const luminance = {
  light: {
    backgroundDefault: 1,
    backgroundTinted: 0.9,
    surfaceDefault: 1,
    surfaceTinted: 0.81,
    surfaceHover: 0.7,
    surfaceActive: 0.6,
    borderSubtle: 0.5,
    borderDefault: 0.21,
    borderStrong: 0.12,
    textSubtle: 0.12,
    textDefault: 0.0245,
    baseDefault: 1,
    baseHover: 1,
    baseActive: 1,
    baseContrastDefault: 1,
    baseContrastSubtle: 1,
  },
  dark: {
    backgroundDefault: 0.011,
    backgroundTinted: 0.017,
    surfaceDefault: 0.025,
    surfaceTinted: 0.035,
    surfaceHover: 0.044,
    surfaceActive: 0.057,
    borderSubtle: 0.082,
    borderDefault: 0.2,
    borderStrong: 0.36,
    textSubtle: 0.36,
    textDefault: 0.78,
    baseDefault: 1,
    baseHover: 1,
    baseActive: 1,
    baseContrastSubtle: 1,
    baseContrastDefault: 1,
  },
  contrast: {
    backgroundDefault: 0.001,
    backgroundTinted: 0.0065,
    surfaceDefault: 0.015,
    surfaceTinted: 0.015,
    surfaceHover: 0.028,
    surfaceActive: 0.045,
    borderSubtle: 0.26,
    borderDefault: 0.4,
    borderStrong: 0.6,
    textSubtle: 0.57,
    textDefault: 0.86,
    baseDefault: 1,
    baseHover: 1,
    baseActive: 1,
    baseContrastSubtle: 1,
    baseContrastDefault: 1,
  },
};
