/**
 * Do not edit directly
 * These files are generated from design tokens defined in Figma using Token Studio
 */

export const color = [
  {
    value: '#feefef',
    type: 'color',
    description: 'AAA 12.8 on grey 800\nAA 6.4 as bkdg for interaction blue',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#feefef',
      type: 'color',
      description: 'AAA 12.8 on grey 800\nAA 6.4 as bkdg for interaction blue',
    },
    name: '--fds-brand-alt1-100',
    attributes: {},
    path: ['brand', 'alt1', '100'],
  },
  {
    value: '#fddfe0',
    type: 'color',
    description:
      'Light error color\nAAA 11.4 on grey 800\nAA 5.7 as bkdg for interaction blue',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#fddfe0',
      type: 'color',
      description:
        'Light error color\nAAA 11.4 on grey 800\nAA 5.7 as bkdg for interaction blue',
    },
    name: '--fds-brand-alt1-200',
    attributes: {},
    path: ['brand', 'alt1', '200'],
  },
  {
    value: '#fbbfc1',
    type: 'color',
    description: 'AAA 9 on grey 800\nAA 4.5 as bkdg for interaction blue',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#fbbfc1',
      type: 'color',
      description: 'AAA 9 on grey 800\nAA 4.5 as bkdg for interaction blue',
    },
    name: '--fds-brand-alt1-300',
    attributes: {},
    path: ['brand', 'alt1', '300'],
  },
  {
    value: '#f89fa1',
    type: 'color',
    description: 'AAA 7.1 on grey 800\nAA18 3.5 as bkdg for interaction blue',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#f89fa1',
      type: 'color',
      description: 'AAA 7.1 on grey 800\nAA18 3.5 as bkdg for interaction blue',
    },
    name: '--fds-brand-alt1-400',
    attributes: {},
    path: ['brand', 'alt1', '400'],
  },
  {
    value: '#f67f82',
    type: 'color',
    description: 'AA 5.6 on grey 800',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#f67f82',
      type: 'color',
      description: 'AA 5.6 on grey 800',
    },
    name: '--fds-brand-alt1-500',
    attributes: {},
    path: ['brand', 'alt1', '500'],
  },
  {
    value: '#f45f63',
    type: 'color',
    description: 'AA 4.5 on grey 800',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#f45f63',
      type: 'color',
      description: 'AA 4.5 on grey 800',
    },
    name: '--fds-brand-alt1-600',
    attributes: {},
    path: ['brand', 'alt1', '600'],
  },
  {
    value: '#dc5659',
    type: 'color',
    description: 'AA18 3.7 on grey 800',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#dc5659',
      type: 'color',
      description: 'AA18 3.7 on grey 800',
    },
    name: '--fds-brand-alt1-700',
    attributes: {},
    path: ['brand', 'alt1', '700'],
  },
  {
    value: '#c34c4f',
    type: 'color',
    description: 'AA 4.7 on white',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#c34c4f',
      type: 'color',
      description: 'AA 4.7 on white',
    },
    name: '--fds-brand-alt1-800',
    attributes: {},
    path: ['brand', 'alt1', '800'],
  },
  {
    value: '#B83D41',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#B83D41',
      type: 'color',
    },
    name: '--fds-brand-alt1-900',
    attributes: {},
    path: ['brand', 'alt1', '900'],
  },
  {
    value: '#fcf7e9',
    type: 'color',
    description: 'AAA 13.3 on grey 800\nAA 6.7 as bkdg for interaction blue',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#fcf7e9',
      type: 'color',
      description: 'AAA 13.3 on grey 800\nAA 6.7 as bkdg for interaction blue',
    },
    name: '--fds-brand-alt2-100',
    attributes: {},
    path: ['brand', 'alt2', '100'],
  },
  {
    value: '#faeec2',
    type: 'color',
    description:
      'Light warning color\nAAA 12.3 on grey 800\nAA 1.1 as bkdg for interaction blue',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#faeec2',
      type: 'color',
      description:
        'Light warning color\nAAA 12.3 on grey 800\nAA 1.1 as bkdg for interaction blue',
    },
    name: '--fds-brand-alt2-200',
    attributes: {},
    path: ['brand', 'alt2', '200'],
  },
  {
    value: '#f5dda6',
    type: 'color',
    description: 'AAA 10 on grey 800\nAA 5.4 as bkdg for interaction blue',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#f5dda6',
      type: 'color',
      description: 'AAA 10 on grey 800\nAA 5.4 as bkdg for interaction blue',
    },
    name: '--fds-brand-alt2-300',
    attributes: {},
    path: ['brand', 'alt2', '300'],
  },
  {
    value: '#efcc79',
    type: 'color',
    description: 'AAA 9.2 on grey 800\nAA 4.6 as bkdg for interaction blue',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#efcc79',
      type: 'color',
      description: 'AAA 9.2 on grey 800\nAA 4.6 as bkdg for interaction blue',
    },
    name: '--fds-brand-alt2-400',
    attributes: {},
    path: ['brand', 'alt2', '400'],
  },
  {
    value: '#eabb4d',
    type: 'color',
    description: 'AAA 7.9 on grey 800\nAA18 4 as bkdg for interaction blue',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#eabb4d',
      type: 'color',
      description: 'AAA 7.9 on grey 800\nAA18 4 as bkdg for interaction blue',
    },
    name: '--fds-brand-alt2-500',
    attributes: {},
    path: ['brand', 'alt2', '500'],
  },
  {
    value: '#e5aa20',
    type: 'color',
    description: 'AA 6.8 on grey 800\nAA18 3.4 as bkdg for interaction blue',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#e5aa20',
      type: 'color',
      description: 'AA 6.8 on grey 800\nAA18 3.4 as bkdg for interaction blue',
    },
    name: '--fds-brand-alt2-600',
    attributes: {},
    path: ['brand', 'alt2', '600'],
  },
  {
    value: '#ce991d',
    type: 'color',
    description: 'AA 5.5 on grey 800',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#ce991d',
      type: 'color',
      description: 'AA 5.5 on grey 800',
    },
    name: '--fds-brand-alt2-700',
    attributes: {},
    path: ['brand', 'alt2', '700'],
  },
  {
    value: '#b7881a',
    type: 'color',
    description: 'AA18 4.4 on grey 800\nAA18 3.2 on white',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#b7881a',
      type: 'color',
      description: 'AA18 4.4 on grey 800\nAA18 3.2 on white',
    },
    name: '--fds-brand-alt2-800',
    attributes: {},
    path: ['brand', 'alt2', '800'],
  },
  {
    value: '#A17717',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#A17717',
      type: 'color',
    },
    name: '--fds-brand-alt2-900',
    attributes: {},
    path: ['brand', 'alt2', '900'],
  },
  {
    value: '#e9f5ff',
    type: 'color',
    description: 'AAA 12.9 on grey 800\nAA 6.5 as bkdg for interaction blue',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#e9f5ff',
      type: 'color',
      description: 'AAA 12.9 on grey 800\nAA 6.5 as bkdg for interaction blue',
    },
    name: '--fds-brand-alt3-100',
    attributes: {},
    path: ['brand', 'alt3', '100'],
  },
  {
    value: '#d2eafd',
    type: 'color',
    description:
      'Light information color \nAAA 11.5 on grey 800\nAA 5.8 as bkdg for interaction blue',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#d2eafd',
      type: 'color',
      description:
        'Light information color \nAAA 11.5 on grey 800\nAA 5.8 as bkdg for interaction blue',
    },
    name: '--fds-brand-alt3-200',
    attributes: {},
    path: ['brand', 'alt3', '200'],
  },
  {
    value: '#a5d6fb',
    type: 'color',
    description: 'AAA 9.2 on grey 800\nAA 4.6 as bkdg for interaction blue',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#a5d6fb',
      type: 'color',
      description: 'AAA 9.2 on grey 800\nAA 4.6 as bkdg for interaction blue',
    },
    name: '--fds-brand-alt3-300',
    attributes: {},
    path: ['brand', 'alt3', '300'],
  },
  {
    value: '#78c1f9',
    type: 'color',
    description: 'AAA 7.3 on grey 800\nAA18 3.7 as bkdg for interaction blue',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#78c1f9',
      type: 'color',
      description: 'AAA 7.3 on grey 800\nAA18 3.7 as bkdg for interaction blue',
    },
    name: '--fds-brand-alt3-400',
    attributes: {},
    path: ['brand', 'alt3', '400'],
  },
  {
    value: '#4badf7',
    type: 'color',
    description: 'AA 5.8 on grey 800',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#4badf7',
      type: 'color',
      description: 'AA 5.8 on grey 800',
    },
    name: '--fds-brand-alt3-500',
    attributes: {},
    path: ['brand', 'alt3', '500'],
  },
  {
    value: '#1e98f5',
    type: 'color',
    description: 'AA 4.6 on grey 800',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#1e98f5',
      type: 'color',
      description: 'AA 4.6 on grey 800',
    },
    name: '--fds-brand-alt3-600',
    attributes: {},
    path: ['brand', 'alt3', '600'],
  },
  {
    value: '#1b88dd',
    type: 'color',
    description: 'AA18 3.8 on grey 800',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#1b88dd',
      type: 'color',
      description: 'AA18 3.8 on grey 800',
    },
    name: '--fds-brand-alt3-700',
    attributes: {},
    path: ['brand', 'alt3', '700'],
  },
  {
    value: '#156aac',
    type: 'color',
    description: 'AA 5.6 on white',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#156aac',
      type: 'color',
      description: 'AA 5.6 on white',
    },
    name: '--fds-brand-alt3-800',
    attributes: {},
    path: ['brand', 'alt3', '800'],
  },
  {
    value: '#125A91',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#125A91',
      type: 'color',
    },
    name: '--fds-brand-alt3-900',
    attributes: {},
    path: ['brand', 'alt3', '900'],
  },
  {
    value: '#fddfe0',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{brand.alt1.200}',
      type: 'color',
    },
    name: '--fds-semantic-surface-first-light',
    attributes: {},
    path: ['semantic', 'surface', 'first', 'light'],
  },
  {
    value: '#fbbfc1',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{brand.alt1.300}',
      type: 'color',
    },
    name: '--fds-semantic-surface-first-light-hover',
    attributes: {},
    path: ['semantic', 'surface', 'first', 'light-hover'],
  },
  {
    value: '#f89fa1',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{brand.alt1.400}',
      type: 'color',
    },
    name: '--fds-semantic-surface-first-light-active',
    attributes: {},
    path: ['semantic', 'surface', 'first', 'light-active'],
  },
  {
    value: '#c34c4f',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{brand.alt1.800}',
      type: 'color',
    },
    name: '--fds-semantic-surface-first-dark',
    attributes: {},
    path: ['semantic', 'surface', 'first', 'dark'],
  },
  {
    value: '#faeec2',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{brand.alt2.200}',
      type: 'color',
    },
    name: '--fds-semantic-surface-second-light',
    attributes: {},
    path: ['semantic', 'surface', 'second', 'light'],
  },
  {
    value: '#f5dda6',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{brand.alt2.300}',
      type: 'color',
    },
    name: '--fds-semantic-surface-second-light-hover',
    attributes: {},
    path: ['semantic', 'surface', 'second', 'light-hover'],
  },
  {
    value: '#efcc79',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{brand.alt2.400}',
      type: 'color',
    },
    name: '--fds-semantic-surface-second-light-active',
    attributes: {},
    path: ['semantic', 'surface', 'second', 'light-active'],
  },
  {
    value: '#A17717',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{brand.alt2.900}',
      type: 'color',
    },
    name: '--fds-semantic-surface-second-dark',
    attributes: {},
    path: ['semantic', 'surface', 'second', 'dark'],
  },
  {
    value: '#d2eafd',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{brand.alt3.200}',
      type: 'color',
    },
    name: '--fds-semantic-surface-third-light',
    attributes: {},
    path: ['semantic', 'surface', 'third', 'light'],
  },
  {
    value: '#a5d6fb',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{brand.alt3.300}',
      type: 'color',
    },
    name: '--fds-semantic-surface-third-light-hover',
    attributes: {},
    path: ['semantic', 'surface', 'third', 'light-hover'],
  },
  {
    value: '#78c1f9',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{brand.alt3.400}',
      type: 'color',
    },
    name: '--fds-semantic-surface-third-light-active',
    attributes: {},
    path: ['semantic', 'surface', 'third', 'light-active'],
  },
  {
    value: '#156aac',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{brand.alt3.800}',
      type: 'color',
    },
    name: '--fds-semantic-surface-third-dark',
    attributes: {},
    path: ['semantic', 'surface', 'third', 'dark'],
  },
  {
    value: '#e6eff8',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{colors.blue.100}',
      type: 'color',
    },
    name: '--fds-semantic-surface-action-first-subtle',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'first', 'subtle'],
  },
  {
    value: '#b3d0ea',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{colors.blue.200}',
      type: 'color',
    },
    name: '--fds-semantic-surface-action-first-subtle-hover',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'first', 'subtle-hover'],
  },
  {
    value: '#0062ba',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{colors.blue.700}',
      type: 'color',
    },
    name: '--fds-semantic-surface-action-first-default',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'first', 'default'],
  },
  {
    value: '#004e95',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{colors.blue.800}',
      type: 'color',
    },
    name: '--fds-semantic-surface-action-first-hover',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'first', 'hover'],
  },
  {
    value: '#00315d',
    type: 'color',
    description: 'Standard farge for handlinger',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{colors.blue.900}',
      type: 'color',
      description: 'Standard farge for handlinger',
    },
    name: '--fds-semantic-surface-action-first-active',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'first', 'active'],
  },
  {
    value: '#ffffff',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{colors.white}',
      type: 'color',
    },
    name: '--fds-semantic-surface-action-first-no_fill',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'first', 'no_fill'],
  },
  {
    value: '#e6eff8',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{colors.blue.100}',
      type: 'color',
    },
    name: '--fds-semantic-surface-action-first-no_fill-hover',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'first', 'no_fill-hover'],
  },
  {
    value: '#b3d0ea',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{colors.blue.200}',
      type: 'color',
    },
    name: '--fds-semantic-surface-action-first-no_fill-active',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'first', 'no_fill-active'],
  },
  {
    value: '#f4f5f6',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{colors.grey.100}',
      type: 'color',
    },
    name: '--fds-semantic-surface-action-second-subtle',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'second', 'subtle'],
  },
  {
    value: '#e9eaec',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{colors.grey.200}',
      type: 'color',
    },
    name: '--fds-semantic-surface-action-second-subtle-hover',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'second', 'subtle-hover'],
  },
  {
    value: '#00315d',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{colors.blue.900}',
      type: 'color',
    },
    name: '--fds-semantic-surface-action-second-default',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'second', 'default'],
  },
  {
    value: 'rgba(0, 49, 93, 0.9)',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: 'rgba({colors.blue.900}, 0.9)',
      type: 'color',
    },
    name: '--fds-semantic-surface-action-second-hover',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'second', 'hover'],
  },
  {
    value: 'rgba(0, 49, 93, 0.8)',
    type: 'color',
    description: 'Standard farge for handlinger',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: 'rgba({colors.blue.900}, 0.8)',
      type: 'color',
      description: 'Standard farge for handlinger',
    },
    name: '--fds-semantic-surface-action-second-active',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'second', 'active'],
  },
  {
    value: '#ffffff',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{colors.white}',
      type: 'color',
    },
    name: '--fds-semantic-surface-action-second-no_fill',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'second', 'no_fill'],
  },
  {
    value: 'rgba(0, 49, 93, 0.1)',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: 'rgba({colors.blue.900}, 0.1)',
      type: 'color',
    },
    name: '--fds-semantic-surface-action-second-no_fill-hover',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'second', 'no_fill-hover'],
  },
  {
    value: 'rgba(0, 49, 93, 0.2)',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: 'rgba({colors.blue.900}, 0.2)',
      type: 'color',
    },
    name: '--fds-semantic-surface-action-second-no_fill-active',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'second', 'no_fill-active'],
  },
  {
    value: '#e6eff8',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.100}',
      type: 'color',
    },
    name: '--fds-semantic-surface-action-subtle',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'subtle'],
  },
  {
    value: '#b3d0ea',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.200}',
      type: 'color',
    },
    name: '--fds-semantic-surface-action-subtle-hover',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'subtle-hover'],
  },
  {
    value: '#0062ba',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.700}',
      type: 'color',
    },
    name: '--fds-semantic-surface-action-default',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'default'],
  },
  {
    value: '#004e95',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.800}',
      type: 'color',
    },
    name: '--fds-semantic-surface-action-hover',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'hover'],
  },
  {
    value: '#00315d',
    type: 'color',
    description: 'Standard farge for handlinger',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.900}',
      type: 'color',
      description: 'Standard farge for handlinger',
    },
    name: '--fds-semantic-surface-action-active',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'active'],
  },
  {
    value: '#ffffff',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.white}',
      type: 'color',
    },
    name: '--fds-semantic-surface-action-no_fill',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'no_fill'],
  },
  {
    value: '#e6eff8',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.100}',
      type: 'color',
    },
    name: '--fds-semantic-surface-action-no_fill-hover',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'no_fill-hover'],
  },
  {
    value: '#b3d0ea',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.200}',
      type: 'color',
    },
    name: '--fds-semantic-surface-action-no_fill-active',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'no_fill-active'],
  },
  {
    value: '#0062ba',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.700}',
      type: 'color',
    },
    name: '--fds-semantic-surface-action-checked',
    attributes: {},
    path: ['semantic', 'surface', 'action', 'checked'],
  },
  {
    value: '#ffffff',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.white}',
      type: 'color',
    },
    name: '--fds-semantic-surface-neutral-default',
    attributes: {},
    path: ['semantic', 'surface', 'neutral', 'default'],
  },
  {
    value: '#e6eff8',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.100}',
      type: 'color',
    },
    name: '--fds-semantic-surface-neutral-selected',
    attributes: {},
    path: ['semantic', 'surface', 'neutral', 'selected'],
  },
  {
    value: '#f4f5f6',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.100}',
      type: 'color',
    },
    name: '--fds-semantic-surface-neutral-subtle',
    attributes: {},
    path: ['semantic', 'surface', 'neutral', 'subtle'],
  },
  {
    value: '#e9eaec',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.200}',
      type: 'color',
    },
    name: '--fds-semantic-surface-neutral-subtle-hover',
    attributes: {},
    path: ['semantic', 'surface', 'neutral', 'subtle-hover'],
  },
  {
    value: '#68707c',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.600}',
      type: 'color',
    },
    name: '--fds-semantic-surface-neutral-dark',
    attributes: {},
    path: ['semantic', 'surface', 'neutral', 'dark'],
  },
  {
    value: '#4b5563',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.700}',
      type: 'color',
    },
    name: '--fds-semantic-surface-neutral-dark-hover',
    attributes: {},
    path: ['semantic', 'surface', 'neutral', 'dark-hover'],
  },
  {
    value: '#1e2b3c',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.800}',
      type: 'color',
    },
    name: '--fds-semantic-surface-neutral-inverted',
    attributes: {},
    path: ['semantic', 'surface', 'neutral', 'inverted'],
  },
  {
    value: '#d1f4e1',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.green.200}',
      type: 'color',
    },
    name: '--fds-semantic-surface-success-subtle',
    attributes: {},
    path: ['semantic', 'surface', 'success', 'subtle'],
  },
  {
    value: '#8be4b5',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.green.300}',
      type: 'color',
    },
    name: '--fds-semantic-surface-success-subtle-hover',
    attributes: {},
    path: ['semantic', 'surface', 'success', 'subtle-hover'],
  },
  {
    value: '#118849',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.green.700}',
      type: 'color',
    },
    name: '--fds-semantic-surface-success-default',
    attributes: {},
    path: ['semantic', 'surface', 'success', 'default'],
  },
  {
    value: '#0c6536',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.green.800}',
      type: 'color',
    },
    name: '--fds-semantic-surface-success-hover',
    attributes: {},
    path: ['semantic', 'surface', 'success', 'hover'],
  },
  {
    value: '#084826',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.green.900}',
      type: 'color',
    },
    name: '--fds-semantic-surface-success-active',
    attributes: {},
    path: ['semantic', 'surface', 'success', 'active'],
  },
  {
    value: '#ffffff',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.white}',
      type: 'color',
    },
    name: '--fds-semantic-surface-success-no_fill',
    attributes: {},
    path: ['semantic', 'surface', 'success', 'no_fill'],
  },
  {
    value: '#d1f4e1',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.green.200}',
      type: 'color',
    },
    name: '--fds-semantic-surface-success-no_fill-hover',
    attributes: {},
    path: ['semantic', 'surface', 'success', 'no_fill-hover'],
  },
  {
    value: '#8be4b5',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.green.300}',
      type: 'color',
    },
    name: '--fds-semantic-surface-success-no_fill-active',
    attributes: {},
    path: ['semantic', 'surface', 'success', 'no_fill-active'],
  },
  {
    value: '#fffbe6',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.yellow.100}',
      type: 'color',
    },
    name: '--fds-semantic-surface-warning-subtle',
    attributes: {},
    path: ['semantic', 'surface', 'warning', 'subtle'],
  },
  {
    value: '#fff4b4',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.yellow.200}',
      type: 'color',
    },
    name: '--fds-semantic-surface-warning-subtle-hover',
    attributes: {},
    path: ['semantic', 'surface', 'warning', 'subtle-hover'],
  },
  {
    value: '#fff4b4',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.yellow.200}',
      type: 'color',
    },
    name: '--fds-semantic-surface-warning-default',
    attributes: {},
    path: ['semantic', 'surface', 'warning', 'default'],
  },
  {
    value: '#ffed83',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.yellow.300}',
      type: 'color',
    },
    name: '--fds-semantic-surface-warning-default-hover',
    attributes: {},
    path: ['semantic', 'surface', 'warning', 'default-hover'],
  },
  {
    value: '#f9d5db',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.red.100}',
      type: 'color',
    },
    name: '--fds-semantic-surface-danger-subtle',
    attributes: {},
    path: ['semantic', 'surface', 'danger', 'subtle'],
  },
  {
    value: '#f3abb6',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.red.200}',
      type: 'color',
    },
    name: '--fds-semantic-surface-danger-subtle-hover',
    attributes: {},
    path: ['semantic', 'surface', 'danger', 'subtle-hover'],
  },
  {
    value: '#e02e49',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.red.500}',
      type: 'color',
    },
    name: '--fds-semantic-surface-danger-default',
    attributes: {},
    path: ['semantic', 'surface', 'danger', 'default'],
  },
  {
    value: '#b3253a',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.red.600}',
      type: 'color',
    },
    name: '--fds-semantic-surface-danger-hover',
    attributes: {},
    path: ['semantic', 'surface', 'danger', 'hover'],
  },
  {
    value: '#861c2c',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.red.700}',
      type: 'color',
    },
    name: '--fds-semantic-surface-danger-active',
    attributes: {},
    path: ['semantic', 'surface', 'danger', 'active'],
  },
  {
    value: '#ffffff',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.white}',
      type: 'color',
    },
    name: '--fds-semantic-surface-danger-no_fill',
    attributes: {},
    path: ['semantic', 'surface', 'danger', 'no_fill'],
  },
  {
    value: '#f9d5db',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.red.100}',
      type: 'color',
    },
    name: '--fds-semantic-surface-danger-no_fill-hover',
    attributes: {},
    path: ['semantic', 'surface', 'danger', 'no_fill-hover'],
  },
  {
    value: '#f3abb6',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.red.200}',
      type: 'color',
    },
    name: '--fds-semantic-surface-danger-no_fill-active',
    attributes: {},
    path: ['semantic', 'surface', 'danger', 'no_fill-active'],
  },
  {
    value: '#e6eff8',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.100}',
      type: 'color',
    },
    name: '--fds-semantic-surface-info-subtle',
    attributes: {},
    path: ['semantic', 'surface', 'info', 'subtle'],
  },
  {
    value: '#b3d0ea',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.200}',
      type: 'color',
    },
    name: '--fds-semantic-surface-info-subtle-hover',
    attributes: {},
    path: ['semantic', 'surface', 'info', 'subtle-hover'],
  },
  {
    value: '#ffffff',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.white}',
      type: 'color',
    },
    name: '--fds-semantic-surface-on_inverted-default',
    attributes: {},
    path: ['semantic', 'surface', 'on_inverted', 'default'],
  },
  {
    value: '#ffffffe6',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '#ffffffe6',
      type: 'color',
    },
    name: '--fds-semantic-surface-on_inverted-hover',
    attributes: {},
    path: ['semantic', 'surface', 'on_inverted', 'hover'],
  },
  {
    value: '#ffffffcc',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '#ffffffcc',
      type: 'color',
    },
    name: '--fds-semantic-surface-on_inverted-active',
    attributes: {},
    path: ['semantic', 'surface', 'on_inverted', 'active'],
  },
  {
    value: '#ffffff00',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '#ffffff00',
      type: 'color',
    },
    name: '--fds-semantic-surface-on_inverted-no_fill',
    attributes: {},
    path: ['semantic', 'surface', 'on_inverted', 'no_fill'],
  },
  {
    value: '#ffffff1a',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '#ffffff1a',
      type: 'color',
    },
    name: '--fds-semantic-surface-on_inverted-no_fill-hover',
    attributes: {},
    path: ['semantic', 'surface', 'on_inverted', 'no_fill-hover'],
  },
  {
    value: '#ffffff33',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '#ffffff33',
      type: 'color',
    },
    name: '--fds-semantic-surface-on_inverted-no_fill-active',
    attributes: {},
    path: ['semantic', 'surface', 'on_inverted', 'no_fill-active'],
  },
  {
    value: '#ffda06',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.yellow.500}',
      type: 'color',
    },
    name: '--fds-semantic-surface-focus-default',
    attributes: {},
    path: ['semantic', 'surface', 'focus', 'default'],
  },
  {
    value: '#f45f63',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{brand.alt1.600}',
      type: 'color',
    },
    name: '--fds-semantic-border-first-default',
    attributes: {},
    path: ['semantic', 'border', 'first', 'default'],
  },
  {
    value: '#dc5659',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{brand.alt1.700}',
      type: 'color',
    },
    name: '--fds-semantic-border-first-hover',
    attributes: {},
    path: ['semantic', 'border', 'first', 'hover'],
  },
  {
    value: '#c34c4f',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{brand.alt1.800}',
      type: 'color',
    },
    name: '--fds-semantic-border-first-active',
    attributes: {},
    path: ['semantic', 'border', 'first', 'active'],
  },
  {
    value: '#e5aa20',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{brand.alt2.600}',
      type: 'color',
    },
    name: '--fds-semantic-border-second-default',
    attributes: {},
    path: ['semantic', 'border', 'second', 'default'],
  },
  {
    value: '#ce991d',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{brand.alt2.700}',
      type: 'color',
    },
    name: '--fds-semantic-border-second-hover',
    attributes: {},
    path: ['semantic', 'border', 'second', 'hover'],
  },
  {
    value: '#b7881a',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{brand.alt2.800}',
      type: 'color',
    },
    name: '--fds-semantic-border-second-active',
    attributes: {},
    path: ['semantic', 'border', 'second', 'active'],
  },
  {
    value: '#1e98f5',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{brand.alt3.600}',
      type: 'color',
    },
    name: '--fds-semantic-border-third-default',
    attributes: {},
    path: ['semantic', 'border', 'third', 'default'],
  },
  {
    value: '#1b88dd',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{brand.alt3.700}',
      type: 'color',
    },
    name: '--fds-semantic-border-third-hover',
    attributes: {},
    path: ['semantic', 'border', 'third', 'hover'],
  },
  {
    value: '#156aac',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{brand.alt3.800}',
      type: 'color',
    },
    name: '--fds-semantic-border-third-active',
    attributes: {},
    path: ['semantic', 'border', 'third', 'active'],
  },
  {
    value: '#b3d0ea',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{colors.blue.200}',
      type: 'color',
    },
    name: '--fds-semantic-border-action-first-subtle',
    attributes: {},
    path: ['semantic', 'border', 'action', 'first', 'subtle'],
  },
  {
    value: '#66a1d6',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{colors.blue.400}',
      type: 'color',
    },
    name: '--fds-semantic-border-action-first-subtle-hover',
    attributes: {},
    path: ['semantic', 'border', 'action', 'first', 'subtle-hover'],
  },
  {
    value: '#0062ba',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{colors.blue.700}',
      type: 'color',
    },
    name: '--fds-semantic-border-action-first-default',
    attributes: {},
    path: ['semantic', 'border', 'action', 'first', 'default'],
  },
  {
    value: '#004e95',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{colors.blue.800}',
      type: 'color',
    },
    name: '--fds-semantic-border-action-first-hover',
    attributes: {},
    path: ['semantic', 'border', 'action', 'first', 'hover'],
  },
  {
    value: '#00315d',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{colors.blue.900}',
      type: 'color',
    },
    name: '--fds-semantic-border-action-first-active',
    attributes: {},
    path: ['semantic', 'border', 'action', 'first', 'active'],
  },
  {
    value: '#e9eaec',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{colors.grey.200}',
      type: 'color',
    },
    name: '--fds-semantic-border-action-second-subtle',
    attributes: {},
    path: ['semantic', 'border', 'action', 'second', 'subtle'],
  },
  {
    value: '#d2d5d8',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{colors.grey.300}',
      type: 'color',
    },
    name: '--fds-semantic-border-action-second-subtle-hover',
    attributes: {},
    path: ['semantic', 'border', 'action', 'second', 'subtle-hover'],
  },
  {
    value: '#00315d',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{colors.blue.900}',
      type: 'color',
    },
    name: '--fds-semantic-border-action-second-default',
    attributes: {},
    path: ['semantic', 'border', 'action', 'second', 'default'],
  },
  {
    value: '#00315d',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{colors.blue.900}',
      type: 'color',
    },
    name: '--fds-semantic-border-action-second-hover',
    attributes: {},
    path: ['semantic', 'border', 'action', 'second', 'hover'],
  },
  {
    value: '#00315d',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{colors.blue.900}',
      type: 'color',
    },
    name: '--fds-semantic-border-action-second-active',
    attributes: {},
    path: ['semantic', 'border', 'action', 'second', 'active'],
  },
  {
    value: '#b3d0ea',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.200}',
      type: 'color',
    },
    name: '--fds-semantic-border-action-subtle',
    attributes: {},
    path: ['semantic', 'border', 'action', 'subtle'],
  },
  {
    value: '#66a1d6',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.400}',
      type: 'color',
    },
    name: '--fds-semantic-border-action-subtle-hover',
    attributes: {},
    path: ['semantic', 'border', 'action', 'subtle-hover'],
  },
  {
    value: '#0062ba',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.700}',
      type: 'color',
    },
    name: '--fds-semantic-border-action-default',
    attributes: {},
    path: ['semantic', 'border', 'action', 'default'],
  },
  {
    value: '#0062ba',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.700}',
      type: 'color',
    },
    name: '--fds-semantic-border-action-hover',
    attributes: {},
    path: ['semantic', 'border', 'action', 'hover'],
  },
  {
    value: '#00315d',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.900}',
      type: 'color',
    },
    name: '--fds-semantic-border-action-active',
    attributes: {},
    path: ['semantic', 'border', 'action', 'active'],
  },
  {
    value: '#00315d',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.900}',
      type: 'color',
    },
    name: '--fds-semantic-border-action-dark',
    attributes: {},
    path: ['semantic', 'border', 'action', 'dark'],
  },
  {
    value: '#0062ba',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.700}',
      type: 'color',
    },
    name: '--fds-semantic-border-action-dark-hover',
    attributes: {},
    path: ['semantic', 'border', 'action', 'dark-hover'],
  },
  {
    value: '#004e95',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.800}',
      type: 'color',
    },
    name: '--fds-semantic-border-info-default',
    attributes: {},
    path: ['semantic', 'border', 'info', 'default'],
  },
  {
    value: '#68707c',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.600}',
      type: 'color',
    },
    name: '--fds-semantic-border-neutral-default',
    attributes: {},
    path: ['semantic', 'border', 'neutral', 'default'],
  },
  {
    value: '#d2d5d8',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.300}',
      type: 'color',
    },
    name: '--fds-semantic-border-neutral-subtle',
    attributes: {},
    path: ['semantic', 'border', 'neutral', 'subtle'],
  },
  {
    value: '#1e2b3c',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.800}',
      type: 'color',
    },
    name: '--fds-semantic-border-neutral-strong',
    attributes: {},
    path: ['semantic', 'border', 'neutral', 'strong'],
  },
  {
    value: '#118849',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.green.700}',
      type: 'color',
    },
    name: '--fds-semantic-border-success-default',
    attributes: {},
    path: ['semantic', 'border', 'success', 'default'],
  },
  {
    value: '#0c6536',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.green.800}',
      type: 'color',
    },
    name: '--fds-semantic-border-success-hover',
    attributes: {},
    path: ['semantic', 'border', 'success', 'hover'],
  },
  {
    value: '#084826',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.green.900}',
      type: 'color',
    },
    name: '--fds-semantic-border-success-active',
    attributes: {},
    path: ['semantic', 'border', 'success', 'active'],
  },
  {
    value: '#cc7005',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.orange.600}',
      type: 'color',
    },
    name: '--fds-semantic-border-warning-default',
    attributes: {},
    path: ['semantic', 'border', 'warning', 'default'],
  },
  {
    value: '#995404',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.orange.700}',
      type: 'color',
    },
    name: '--fds-semantic-border-warning-hover',
    attributes: {},
    path: ['semantic', 'border', 'warning', 'hover'],
  },
  {
    value: '#663802',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.orange.800}',
      type: 'color',
    },
    name: '--fds-semantic-border-warning-active',
    attributes: {},
    path: ['semantic', 'border', 'warning', 'active'],
  },
  {
    value: '#e02e49',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.red.500}',
      type: 'color',
    },
    name: '--fds-semantic-border-danger-default',
    attributes: {},
    path: ['semantic', 'border', 'danger', 'default'],
  },
  {
    value: '#b3253a',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.red.600}',
      type: 'color',
    },
    name: '--fds-semantic-border-danger-hover',
    attributes: {},
    path: ['semantic', 'border', 'danger', 'hover'],
  },
  {
    value: '#861c2c',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.red.700}',
      type: 'color',
    },
    name: '--fds-semantic-border-danger-active',
    attributes: {},
    path: ['semantic', 'border', 'danger', 'active'],
  },
  {
    value: '#ffda06',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.yellow.500}',
      type: 'color',
    },
    name: '--fds-semantic-border-focus-outline',
    attributes: {},
    path: ['semantic', 'border', 'focus', 'outline'],
  },
  {
    value: '#1e2b3c',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{semantic.border.neutral.strong}',
      type: 'color',
    },
    name: '--fds-semantic-border-focus-boxshadow',
    attributes: {},
    path: ['semantic', 'border', 'focus', 'boxshadow'],
  },
  {
    value: '#ffffff',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.white}',
      type: 'color',
    },
    name: '--fds-semantic-border-on_inverted-default',
    attributes: {},
    path: ['semantic', 'border', 'on_inverted', 'default'],
  },
  {
    value: '#00315d',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.900}',
      type: 'color',
    },
    name: '--fds-semantic-border-input-default',
    attributes: {},
    path: ['semantic', 'border', 'input', 'default'],
  },
  {
    value: '#0062ba',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.700}',
      type: 'color',
    },
    name: '--fds-semantic-border-input-hover',
    attributes: {},
    path: ['semantic', 'border', 'input', 'hover'],
  },
  {
    value: '#bcbfc5',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.400}',
      type: 'color',
    },
    name: '--fds-semantic-border-divider-default',
    attributes: {},
    path: ['semantic', 'border', 'divider', 'default'],
  },
  {
    value: '#d2d5d8',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.300}',
      type: 'color',
    },
    name: '--fds-semantic-border-divider-subtle',
    attributes: {},
    path: ['semantic', 'border', 'divider', 'subtle'],
  },
  {
    value: '#68707c',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.600}',
      type: 'color',
    },
    name: '--fds-semantic-border-divider-strong',
    attributes: {},
    path: ['semantic', 'border', 'divider', 'strong'],
  },
  {
    value: '#0062ba',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{colors.blue.700}',
      type: 'color',
    },
    name: '--fds-semantic-text-action-first-default',
    attributes: {},
    path: ['semantic', 'text', 'action', 'first', 'default'],
  },
  {
    value: '#004e95',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#004e95',
      type: 'color',
    },
    name: '--fds-semantic-text-action-first-hover',
    attributes: {},
    path: ['semantic', 'text', 'action', 'first', 'hover'],
  },
  {
    value: '#00315d',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '#00315d',
      type: 'color',
    },
    name: '--fds-semantic-text-action-first-active',
    attributes: {},
    path: ['semantic', 'text', 'action', 'first', 'active'],
  },
  {
    value: '#ffffff',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{colors.white}',
      type: 'color',
    },
    name: '--fds-semantic-text-action-first-on_action',
    attributes: {},
    path: ['semantic', 'text', 'action', 'first', 'on_action'],
  },
  {
    value: '#00315d',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{colors.blue.900}',
      type: 'color',
    },
    name: '--fds-semantic-text-action-second-default',
    attributes: {},
    path: ['semantic', 'text', 'action', 'second', 'default'],
  },
  {
    value: '#00315d',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{colors.blue.900}',
      type: 'color',
    },
    name: '--fds-semantic-text-action-second-hover',
    attributes: {},
    path: ['semantic', 'text', 'action', 'second', 'hover'],
  },
  {
    value: '#00315d',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{colors.blue.900}',
      type: 'color',
    },
    name: '--fds-semantic-text-action-second-active',
    attributes: {},
    path: ['semantic', 'text', 'action', 'second', 'active'],
  },
  {
    value: '#ffffff',
    type: 'color',
    filePath: '../../design-tokens/Brand/Digdir.json',
    isSource: false,
    original: {
      value: '{colors.white}',
      type: 'color',
    },
    name: '--fds-semantic-text-action-second-on_action',
    attributes: {},
    path: ['semantic', 'text', 'action', 'second', 'on_action'],
  },
  {
    value: '#0062ba',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.700}',
      type: 'color',
    },
    name: '--fds-semantic-text-action-default',
    attributes: {},
    path: ['semantic', 'text', 'action', 'default'],
  },
  {
    value: '#004e95',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.800}',
      type: 'color',
    },
    name: '--fds-semantic-text-action-hover',
    attributes: {},
    path: ['semantic', 'text', 'action', 'hover'],
  },
  {
    value: '#00315d',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.blue.900}',
      type: 'color',
    },
    name: '--fds-semantic-text-action-active',
    attributes: {},
    path: ['semantic', 'text', 'action', 'active'],
  },
  {
    value: '#ffffff',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.white}',
      type: 'color',
    },
    name: '--fds-semantic-text-action-on_action',
    attributes: {},
    path: ['semantic', 'text', 'action', 'on_action'],
  },
  {
    value: '#0c6536',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.green.800}',
      type: 'color',
    },
    name: '--fds-semantic-text-success-default',
    attributes: {},
    path: ['semantic', 'text', 'success', 'default'],
  },
  {
    value: '#084826',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.green.900}',
      type: 'color',
    },
    name: '--fds-semantic-text-success-hover',
    attributes: {},
    path: ['semantic', 'text', 'success', 'hover'],
  },
  {
    value: '#084826',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.green.900}',
      type: 'color',
    },
    name: '--fds-semantic-text-success-active',
    attributes: {},
    path: ['semantic', 'text', 'success', 'active'],
  },
  {
    value: '#ffffff',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.white}',
      type: 'color',
    },
    name: '--fds-semantic-text-success-on_success',
    attributes: {},
    path: ['semantic', 'text', 'success', 'on_success'],
  },
  {
    value: '#1e2b3c',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.800}',
      type: 'color',
    },
    name: '--fds-semantic-text-success-on_success_subtle',
    attributes: {},
    path: ['semantic', 'text', 'success', 'on_success_subtle'],
  },
  {
    value: '#1e2b3c',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.800}',
      type: 'color',
    },
    name: '--fds-semantic-text-neutral-default',
    attributes: {},
    path: ['semantic', 'text', 'neutral', 'default'],
  },
  {
    value: '#4b5563',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.700}',
      type: 'color',
    },
    name: '--fds-semantic-text-neutral-subtle',
    attributes: {},
    path: ['semantic', 'text', 'neutral', 'subtle'],
  },
  {
    value: '#ffffff',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.white}',
      type: 'color',
    },
    name: '--fds-semantic-text-neutral-on_inverted',
    attributes: {},
    path: ['semantic', 'text', 'neutral', 'on_inverted'],
  },
  {
    value: '#995404',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.orange.700}',
      type: 'color',
    },
    name: '--fds-semantic-text-warning-default',
    attributes: {},
    path: ['semantic', 'text', 'warning', 'default'],
  },
  {
    value: '#cc7005',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.orange.600}',
      type: 'color',
    },
    name: '--fds-semantic-text-warning-icon_warning',
    attributes: {},
    path: ['semantic', 'text', 'warning', 'icon_warning'],
  },
  {
    value: '#663802',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.orange.800}',
      type: 'color',
    },
    name: '--fds-semantic-text-warning-on_warning',
    attributes: {},
    path: ['semantic', 'text', 'warning', 'on_warning'],
  },
  {
    value: '#b3253a',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.red.600}',
      type: 'color',
    },
    name: '--fds-semantic-text-danger-default',
    attributes: {},
    path: ['semantic', 'text', 'danger', 'default'],
  },
  {
    value: '#861c2c',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.red.700}',
      type: 'color',
    },
    name: '--fds-semantic-text-danger-hover',
    attributes: {},
    path: ['semantic', 'text', 'danger', 'hover'],
  },
  {
    value: '#5a121d',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.red.800}',
      type: 'color',
    },
    name: '--fds-semantic-text-danger-active',
    attributes: {},
    path: ['semantic', 'text', 'danger', 'active'],
  },
  {
    value: '#ffffff',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.white}',
      type: 'color',
    },
    name: '--fds-semantic-text-danger-on_danger',
    attributes: {},
    path: ['semantic', 'text', 'danger', 'on_danger'],
  },
  {
    value: '#1e2b3c',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.800}',
      type: 'color',
    },
    name: '--fds-semantic-text-danger-on_danger_subtle',
    attributes: {},
    path: ['semantic', 'text', 'danger', 'on_danger_subtle'],
  },
  {
    value: '#7a1265',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.purple.700}',
      type: 'color',
    },
    name: '--fds-semantic-text-visited-default',
    attributes: {},
    path: ['semantic', 'text', 'visited', 'default'],
  },
  {
    value: '#ffffff',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.white}',
      type: 'color',
    },
    name: '--fds-semantic-background-default',
    attributes: {},
    path: ['semantic', 'background', 'default'],
  },
  {
    value: '#f4f5f6',
    type: 'color',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{colors.grey.100}',
      type: 'color',
    },
    name: '--fds-semantic-background-subtle',
    attributes: {},
    path: ['semantic', 'background', 'subtle'],
  },
];

export const typography = [
  {
    value: "500 clamp(1.94rem, calc(1.88vw + 1.56rem), 3.16rem)/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.medium}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f7}',
      },
      type: 'typography',
    },
    name: '--fds-typography-heading-3xlarge',
    attributes: {},
    path: ['typography', 'heading', '3xlarge'],
  },
  {
    value: "500 clamp(1.78rem, calc(1.44vw + 1.49rem), 2.72rem)/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.medium}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f6}',
      },
      type: 'typography',
    },
    name: '--fds-typography-heading-2xlarge',
    attributes: {},
    path: ['typography', 'heading', '2xlarge'],
  },
  {
    value: "500 clamp(1.59rem, calc(1.15vw + 1.36rem), 2.34rem)/1.3 'Inter'",
    type: 'typography',
    description: 'H1',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.medium}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f5}',
      },
      type: 'typography',
      description: 'H1',
    },
    name: '--fds-typography-heading-xlarge',
    attributes: {},
    path: ['typography', 'heading', 'xlarge'],
  },
  {
    value: "500 clamp(1.47rem, calc(0.86vw + 1.30rem), 2.03rem)/1.3 'Inter'",
    type: 'typography',
    description: 'H2',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.medium}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f4}',
      },
      type: 'typography',
      description: 'H2',
    },
    name: '--fds-typography-heading-large',
    attributes: {},
    path: ['typography', 'heading', 'large'],
  },
  {
    value: "500 clamp(1.34rem, calc(0.63vw + 1.22rem), 1.75rem)/1.3 'Inter'",
    type: 'typography',
    description: 'H3',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.medium}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f3}',
      },
      type: 'typography',
      description: 'H3',
    },
    name: '--fds-typography-heading-medium',
    attributes: {},
    path: ['typography', 'heading', 'medium'],
  },
  {
    value: "500 clamp(1.22rem, calc(0.43vw + 1.13rem), 1.50rem)/1.3 'Inter'",
    type: 'typography',
    description: 'H4',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.medium}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f2}',
      },
      type: 'typography',
      description: 'H4',
    },
    name: '--fds-typography-heading-small',
    attributes: {},
    path: ['typography', 'heading', 'small'],
  },
  {
    value: "500 clamp(1.09rem, calc(0.34vw + 1.03rem), 1.31rem)/1.3 'Inter'",
    type: 'typography',
    description: 'H5',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.medium}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f1}',
      },
      type: 'typography',
      description: 'H5',
    },
    name: '--fds-typography-heading-xsmall',
    attributes: {},
    path: ['typography', 'heading', 'xsmall'],
  },
  {
    value: "500 clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem)/1.3 'Inter'",
    type: 'typography',
    description: 'H6',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.medium}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f0}',
      },
      type: 'typography',
      description: 'H6',
    },
    name: '--fds-typography-heading-xxsmall',
    attributes: {},
    path: ['typography', 'heading', 'xxsmall'],
  },
  {
    value: "400 clamp(1.09rem, calc(0.34vw + 1.03rem), 1.31rem)/1.6 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.600}',
        fontSize: '{font-size.f1}',
      },
      type: 'typography',
    },
    name: '--fds-typography-ingress-medium',
    attributes: {},
    path: ['typography', 'ingress', 'medium'],
  },
  {
    value: "400 clamp(1.09rem, calc(0.34vw + 1.03rem), 1.31rem)/1.5 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.500}',
        fontSize: '{font-size.f1}',
      },
      type: 'typography',
    },
    name: '--fds-typography-paragraph-large',
    attributes: {},
    path: ['typography', 'paragraph', 'large'],
  },
  {
    value: "400 clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem)/1.5 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.500}',
        fontSize: '{font-size.f0}',
      },
      type: 'typography',
    },
    name: '--fds-typography-paragraph-medium',
    attributes: {},
    path: ['typography', 'paragraph', 'medium'],
  },
  {
    value: "400 clamp(0.91rem, calc(0.10vw + 0.89rem), 0.97rem)/1.5 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.500}',
        fontSize: '{font-size.f-1}',
      },
      type: 'typography',
    },
    name: '--fds-typography-paragraph-small',
    attributes: {},
    path: ['typography', 'paragraph', 'small'],
  },
  {
    value: "400 clamp(0.81rem, calc(0.05vw + 0.80rem), 0.84rem)/1.5 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.500}',
        fontSize: '{font-size.f-2}',
      },
      type: 'typography',
    },
    name: '--fds-typography-paragraph-xsmall',
    attributes: {},
    path: ['typography', 'paragraph', 'xsmall'],
  },
  {
    value: "400 clamp(1.09rem, calc(0.34vw + 1.03rem), 1.31rem)/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f1}',
      },
      type: 'typography',
    },
    name: '--fds-typography-paragraph-short-large',
    attributes: {},
    path: ['typography', 'paragraph', 'short', 'large'],
  },
  {
    value: "400 clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem)/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f0}',
      },
      type: 'typography',
    },
    name: '--fds-typography-paragraph-short-medium',
    attributes: {},
    path: ['typography', 'paragraph', 'short', 'medium'],
  },
  {
    value: "400 clamp(0.91rem, calc(0.10vw + 0.89rem), 0.97rem)/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f-1}',
      },
      type: 'typography',
    },
    name: '--fds-typography-paragraph-short-small',
    attributes: {},
    path: ['typography', 'paragraph', 'short', 'small'],
  },
  {
    value: "400 clamp(0.81rem, calc(0.05vw + 0.80rem), 0.84rem)/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f-2}',
      },
      type: 'typography',
    },
    name: '--fds-typography-paragraph-short-xsmall',
    attributes: {},
    path: ['typography', 'paragraph', 'short', 'xsmall'],
  },
  {
    value: "500 clamp(1.09rem, calc(0.34vw + 1.03rem), 1.31rem)/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.medium}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f1}',
      },
      type: 'typography',
    },
    name: '--fds-typography-label-large',
    attributes: {},
    path: ['typography', 'label', 'large'],
  },
  {
    value: "500 clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem)/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.medium}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f0}',
      },
      type: 'typography',
    },
    name: '--fds-typography-label-medium',
    attributes: {},
    path: ['typography', 'label', 'medium'],
  },
  {
    value: "500 clamp(0.91rem, calc(0.10vw + 0.89rem), 0.97rem)/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.medium}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f-1}',
      },
      type: 'typography',
    },
    name: '--fds-typography-label-small',
    attributes: {},
    path: ['typography', 'label', 'small'],
  },
  {
    value: "500 clamp(0.81rem, calc(0.05vw + 0.80rem), 0.84rem)/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.medium}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f-2}',
      },
      type: 'typography',
    },
    name: '--fds-typography-label-xsmall',
    attributes: {},
    path: ['typography', 'label', 'xsmall'],
  },
  {
    value: "400 clamp(1.09rem, calc(0.34vw + 1.03rem), 1.31rem)/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f1}',
      },
      type: 'typography',
    },
    name: '--fds-typography-error_message-large',
    attributes: {},
    path: ['typography', 'error_message', 'large'],
  },
  {
    value: "400 clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem)/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f0}',
      },
      type: 'typography',
    },
    name: '--fds-typography-error_message-medium',
    attributes: {},
    path: ['typography', 'error_message', 'medium'],
  },
  {
    value: "400 clamp(0.91rem, calc(0.10vw + 0.89rem), 0.97rem)/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f-1}',
      },
      type: 'typography',
    },
    name: '--fds-typography-error_message-small',
    attributes: {},
    path: ['typography', 'error_message', 'small'],
  },
  {
    value: "400 clamp(0.81rem, calc(0.05vw + 0.80rem), 0.84rem)/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-size.f-2}',
      },
      type: 'typography',
    },
    name: '--fds-typography-error_message-xsmall',
    attributes: {},
    path: ['typography', 'error_message', 'xsmall'],
  },
  {
    value: "400 1.5rem/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-static.large}',
      },
      type: 'typography',
    },
    name: '--fds-typography-interactive-large',
    attributes: {},
    path: ['typography', 'interactive', 'large'],
  },
  {
    value: "400 1.125rem/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-static.medium}',
      },
      type: 'typography',
    },
    name: '--fds-typography-interactive-medium',
    attributes: {},
    path: ['typography', 'interactive', 'medium'],
  },
  {
    value: "400 1rem/1.3 'Inter'",
    type: 'typography',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: {
        fontFamily: '{fontFamilies.inter}',
        fontWeight: '{fontWeights.regular}',
        lineHeight: '{lineHeights.300}',
        fontSize: '{font-static.small}',
      },
      type: 'typography',
    },
    name: '--fds-typography-interactive-small',
    attributes: {},
    path: ['typography', 'interactive', 'small'],
  },
];

export const opacity = [
  {
    value: '30%',
    type: 'opacity',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '30%',
      type: 'opacity',
    },
    name: '--fds-opacity-disabled',
    attributes: {},
    path: ['opacity', 'disabled'],
  },
];

export const borderRadius = [
  {
    value: '4px',
    type: 'borderRadius',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{border_radius.medium}',
      type: 'borderRadius',
    },
    name: '--fds-border_radius-interactive',
    attributes: {},
    path: ['border_radius', 'interactive'],
  },
  {
    value: '2px',
    type: 'borderRadius',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '2px',
      type: 'borderRadius',
    },
    name: '--fds-border_radius-small',
    attributes: {},
    path: ['border_radius', 'small'],
  },
  {
    value: '4px',
    type: 'borderRadius',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '4px',
      type: 'borderRadius',
    },
    name: '--fds-border_radius-medium',
    attributes: {},
    path: ['border_radius', 'medium'],
  },
  {
    value: '8px',
    type: 'borderRadius',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '8px',
      type: 'borderRadius',
    },
    name: '--fds-border_radius-large',
    attributes: {},
    path: ['border_radius', 'large'],
  },
  {
    value: '12px',
    type: 'borderRadius',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '12px',
      type: 'borderRadius',
    },
    name: '--fds-border_radius-xlarge',
    attributes: {},
    path: ['border_radius', 'xlarge'],
  },
  {
    value: '16px',
    type: 'borderRadius',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '16px',
      type: 'borderRadius',
    },
    name: '--fds-border_radius-xxlarge',
    attributes: {},
    path: ['border_radius', 'xxlarge'],
  },
  {
    value: '24px',
    type: 'borderRadius',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '24px',
      type: 'borderRadius',
    },
    name: '--fds-border_radius-xxxlarge',
    attributes: {},
    path: ['border_radius', 'xxxlarge'],
  },
  {
    value: '32px',
    type: 'borderRadius',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '32px',
      type: 'borderRadius',
    },
    name: '--fds-border_radius-xxxxlarge',
    attributes: {},
    path: ['border_radius', 'xxxxlarge'],
  },
  {
    value: '9999px',
    type: 'borderRadius',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '9999px',
      type: 'borderRadius',
    },
    name: '--fds-border_radius-full',
    attributes: {},
    path: ['border_radius', 'full'],
  },
];

export const spacing = [
  {
    value: '0',
    type: 'spacing',
    description: '0',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '0',
      type: 'spacing',
      description: '0',
    },
    name: '--fds-spacing-0',
    attributes: {},
    path: ['spacing', '0'],
  },
  {
    value: 'calc(4/16*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'spacing',
    description: '4px - 4.5px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_spacing}/16*{font-size.f0}',
      type: 'spacing',
      description: '4px - 4.5px',
    },
    name: '--fds-spacing-1',
    attributes: {},
    path: ['spacing', '1'],
  },
  {
    value: 'calc(4*2/16*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'spacing',
    description: '8px - 9px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_spacing}*2/16*{font-size.f0}',
      type: 'spacing',
      description: '8px - 9px',
    },
    name: '--fds-spacing-2',
    attributes: {},
    path: ['spacing', '2'],
  },
  {
    value: 'calc(4*3/16*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'spacing',
    description: '12px - 13.5px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_spacing}*3/16*{font-size.f0}',
      type: 'spacing',
      description: '12px - 13.5px',
    },
    name: '--fds-spacing-3',
    attributes: {},
    path: ['spacing', '3'],
  },
  {
    value: 'calc(4*4/16*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'spacing',
    description: '16px - 18px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_spacing}*4/16*{font-size.f0}',
      type: 'spacing',
      description: '16px - 18px',
    },
    name: '--fds-spacing-4',
    attributes: {},
    path: ['spacing', '4'],
  },
  {
    value: 'calc(4*5/16*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'spacing',
    description: '20px - 22.5px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_spacing}*5/16*{font-size.f0}',
      type: 'spacing',
      description: '20px - 22.5px',
    },
    name: '--fds-spacing-5',
    attributes: {},
    path: ['spacing', '5'],
  },
  {
    value: 'calc(4*6/16*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'spacing',
    description: '24px - 27px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_spacing}*6/16*{font-size.f0}',
      type: 'spacing',
      description: '24px - 27px',
    },
    name: '--fds-spacing-6',
    attributes: {},
    path: ['spacing', '6'],
  },
  {
    value: 'calc(4*7/16*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'spacing',
    description: '28px - 31.5px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_spacing}*7/16*{font-size.f0}',
      type: 'spacing',
      description: '28px - 31.5px',
    },
    name: '--fds-spacing-7',
    attributes: {},
    path: ['spacing', '7'],
  },
  {
    value: 'calc((4*8/16)*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'spacing',
    description: '32px - 36px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '({base_spacing}*8/16)*{font-size.f0}',
      type: 'spacing',
      description: '32px - 36px',
    },
    name: '--fds-spacing-8',
    attributes: {},
    path: ['spacing', '8'],
  },
  {
    value: 'calc((4*10/16)*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'spacing',
    description: '40px - 45px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '({base_spacing}*10/16)*{font-size.f0}',
      type: 'spacing',
      description: '40px - 45px',
    },
    name: '--fds-spacing-10',
    attributes: {},
    path: ['spacing', '10'],
  },
  {
    value: 'calc((4*12/16)*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'spacing',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '({base_spacing}*12/16)*{font-size.f0}',
      type: 'spacing',
    },
    name: '--fds-spacing-12',
    attributes: {},
    path: ['spacing', '12'],
  },
  {
    value: 'calc((4*14/16)*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'spacing',
    description: '56px - 63px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '({base_spacing}*14/16)*{font-size.f0}',
      type: 'spacing',
      description: '56px - 63px',
    },
    name: '--fds-spacing-14',
    attributes: {},
    path: ['spacing', '14'],
  },
  {
    value: 'calc((4*18/16)*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'spacing',
    description: '72px - 81px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '({base_spacing}*18/16)*{font-size.f0}',
      type: 'spacing',
      description: '72px - 81px',
    },
    name: '--fds-spacing-18',
    attributes: {},
    path: ['spacing', '18'],
  },
  {
    value: 'calc((4*22/16)*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'spacing',
    description: '88px - 99px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '({base_spacing}*22/16)*{font-size.f0}',
      type: 'spacing',
      description: '88px - 99px',
    },
    name: '--fds-spacing-22',
    attributes: {},
    path: ['spacing', '22'],
  },
  {
    value: 'calc((4*26/16)*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'spacing',
    description: '104px - 117px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '({base_spacing}*26/16)*{font-size.f0}',
      type: 'spacing',
      description: '104px - 117px',
    },
    name: '--fds-spacing-26',
    attributes: {},
    path: ['spacing', '26'],
  },
  {
    value: 'calc((4*30/16)*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'spacing',
    description: '120px - 135px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '({base_spacing}*30/16)*{font-size.f0}',
      type: 'spacing',
      description: '120px - 135px',
    },
    name: '--fds-spacing-30',
    attributes: {},
    path: ['spacing', '30'],
  },
];

export const sizing = [
  {
    value: 'calc(4/16*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'sizing',
    description: '4px - 4.5px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_sizing}/16*{font-size.f0}',
      type: 'sizing',
      description: '4px - 4.5px',
    },
    name: '--fds-sizing-1',
    attributes: {},
    path: ['sizing', '1'],
  },
  {
    value: 'calc(4*2/16*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'sizing',
    description: '8px - 9px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_sizing}*2/16*{font-size.f0}',
      type: 'sizing',
      description: '8px - 9px',
    },
    name: '--fds-sizing-2',
    attributes: {},
    path: ['sizing', '2'],
  },
  {
    value: 'calc(4*3/16*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'sizing',
    description: '12px - 13.5px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_sizing}*3/16*{font-size.f0}',
      type: 'sizing',
      description: '12px - 13.5px',
    },
    name: '--fds-sizing-3',
    attributes: {},
    path: ['sizing', '3'],
  },
  {
    value: 'calc(4*4/16*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'sizing',
    description: '16px - 18px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_sizing}*4/16*{font-size.f0}',
      type: 'sizing',
      description: '16px - 18px',
    },
    name: '--fds-sizing-4',
    attributes: {},
    path: ['sizing', '4'],
  },
  {
    value: 'calc(4*5/16*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'sizing',
    description: '20px - 22.5',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_sizing}*5/16*{font-size.f0}',
      type: 'sizing',
      description: '20px - 22.5',
    },
    name: '--fds-sizing-5',
    attributes: {},
    path: ['sizing', '5'],
  },
  {
    value: 'calc(4*6/16*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'sizing',
    description: '24px - 27px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_sizing}*6/16*{font-size.f0}',
      type: 'sizing',
      description: '24px - 27px',
    },
    name: '--fds-sizing-6',
    attributes: {},
    path: ['sizing', '6'],
  },
  {
    value: 'calc(4*7/16*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'sizing',
    description: '28px - 31.5px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_sizing}*7/16*{font-size.f0}',
      type: 'sizing',
      description: '28px - 31.5px',
    },
    name: '--fds-sizing-7',
    attributes: {},
    path: ['sizing', '7'],
  },
  {
    value: 'calc(4*8/16*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'sizing',
    description: '32px - 36px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_sizing}*8/16*{font-size.f0}',
      type: 'sizing',
      description: '32px - 36px',
    },
    name: '--fds-sizing-8',
    attributes: {},
    path: ['sizing', '8'],
  },
  {
    value: 'calc(4*10/16*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'sizing',
    description: '40px - 45px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{base_sizing}*10/16*{font-size.f0}',
      type: 'sizing',
      description: '40px - 45px',
    },
    name: '--fds-sizing-10',
    attributes: {},
    path: ['sizing', '10'],
  },
  {
    value: 'calc((4*12/16)*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'sizing',
    description: '48px - 54px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '({base_sizing}*12/16)*{font-size.f0}',
      type: 'sizing',
      description: '48px - 54px',
    },
    name: '--fds-sizing-12',
    attributes: {},
    path: ['sizing', '12'],
  },
  {
    value: 'calc((4*14/16)*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'sizing',
    description: '56px - 63px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '({base_sizing}*14/16)*{font-size.f0}',
      type: 'sizing',
      description: '56px - 63px',
    },
    name: '--fds-sizing-14',
    attributes: {},
    path: ['sizing', '14'],
  },
  {
    value: 'calc((4*18/16)*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'sizing',
    description: '72px - 81px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '({base_sizing}*18/16)*{font-size.f0}',
      type: 'sizing',
      description: '72px - 81px',
    },
    name: '--fds-sizing-18',
    attributes: {},
    path: ['sizing', '18'],
  },
  {
    value: 'calc((4*22/16)*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'sizing',
    description: '88px - 99px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '({base_sizing}*22/16)*{font-size.f0}',
      type: 'sizing',
      description: '88px - 99px',
    },
    name: '--fds-sizing-22',
    attributes: {},
    path: ['sizing', '22'],
  },
  {
    value: 'calc((4*26/16)*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'sizing',
    description: '104px - 117px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '({base_sizing}*26/16)*{font-size.f0}',
      type: 'sizing',
      description: '104px - 117px',
    },
    name: '--fds-sizing-26',
    attributes: {},
    path: ['sizing', '26'],
  },
  {
    value: 'calc((4*30/16)*clamp(1.00rem, calc(0.19vw + 0.96rem), 1.13rem))',
    type: 'sizing',
    description: '120px - 135px',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '({base_sizing}*30/16)*{font-size.f0}',
      type: 'sizing',
      description: '120px - 135px',
    },
    name: '--fds-sizing-30',
    attributes: {},
    path: ['sizing', '30'],
  },
];

export const borderWidth = [
  {
    value: '1px',
    type: 'borderWidth',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{border_width.1}',
      type: 'borderWidth',
    },
    name: '--fds-border_width-default',
    attributes: {},
    path: ['border_width', 'default'],
  },
  {
    value: '2px',
    type: 'borderWidth',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{border_width.2}',
      type: 'borderWidth',
    },
    name: '--fds-border_width-active',
    attributes: {},
    path: ['border_width', 'active'],
  },
  {
    value: '2px',
    type: 'borderWidth',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '2px',
      type: 'borderWidth',
    },
    name: '--fds-border_width-tab_focus',
    attributes: {},
    path: ['border_width', 'tab_focus'],
  },
];

export const boxShadow = [
  {
    value: '0 0 1px 0 rgba(0,0,0,0.16), 0 1px 2px 0 rgba(0,0,0,0.12)',
    type: 'boxShadow',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{shadow.100}',
      type: 'boxShadow',
    },
    name: '--fds-shadow-xsmall',
    attributes: {},
    path: ['shadow', 'xsmall'],
  },
  {
    value:
      '0 0 1px 0 rgba(0,0,0,0.15), 0 1px 2px 0 rgba(0,0,0,0.12), 0 2px 4px 0 rgba(0,0,0,0.1)',
    type: 'boxShadow',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{shadow.200}',
      type: 'boxShadow',
    },
    name: '--fds-shadow-small',
    attributes: {},
    path: ['shadow', 'small'],
  },
  {
    value:
      '0 0 1px 0 rgba(0,0,0,0.14), 0 2px 4px 0 rgba(0,0,0,0.12), 0 4px 8px 0 rgba(0,0,0,0.12)',
    type: 'boxShadow',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{shadow.300}',
      type: 'boxShadow',
    },
    name: '--fds-shadow-medium',
    attributes: {},
    path: ['shadow', 'medium'],
  },
  {
    value:
      '0 0 1px 0 rgba(0,0,0,0.13), 0 3px 5px 0 rgba(0,0,0,0.13), 0 6px 12px 0 rgba(0,0,0,0.14)',
    type: 'boxShadow',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{shadow.400}',
      type: 'boxShadow',
    },
    name: '--fds-shadow-large',
    attributes: {},
    path: ['shadow', 'large'],
  },
  {
    value:
      '0 0 1px 0 rgba(0,0,0,0.12), 0 4px 8px 0 rgba(0,0,0,0.16), 0 12px 24px 0 rgba(0,0,0,0.16)',
    type: 'boxShadow',
    filePath: '../../design-tokens/Base/Semantic.json',
    isSource: false,
    original: {
      value: '{shadow.500}',
      type: 'boxShadow',
    },
    name: '--fds-shadow-xlarge',
    attributes: {},
    path: ['shadow', 'xlarge'],
  },
];
