export const ColorIndexes = {
  backgroundDefault: 0,
  backgroundTinted: 1,
  surfaceDefault: 2,
  surfaceTinted: 3,
  surfaceHover: 4,
  surfaceActive: 5,
  borderSubtle: 6,
  borderDefault: 7,
  borderStrong: 8,
  textSubtle: 9,
  textDefault: 10,
  baseDefault: 11,
  baseHover: 12,
  baseActive: 13,
  baseContrastSubtle: 14,
  baseContrastDefault: 15,
};

export const ColorScaleNames = [
  'Red',
  'Pure Orange',
  'Light Orange',
  'Yellow',
  'Pale Green',
  'Green',
  'Cyan',
  'Blue',
  'Strong Blue',
  'Purple',
  'Pink',
];
